### PR TITLE
Fix PHPDocs

### PR DESCRIPTION
**Pull request by Crease29**
### 1. Why is this change necessary?

Improve the quality of PHPDocs.

### 2. What does this change do, exactly?

- Fix some wrong `@throws` tags
- Fix and add `@return` tags
- Fix and add `@param` tags
- Remove wrong PHPDoc tags

### 3. Describe each step to reproduce the issue or behaviour.

➖ 

### 4. Please link to the relevant issues (if any).

➖ 

### 5. Which documentation changes (if any) need to be made because of this PR?

➖ 

### 6. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Crease29** [comment]
Okay, fair enough. I'll revert the `@throws` changes. The other changes are okay?

**Comment by mitelg** [comment]
yes :+1:

**Comment by shyim** [comment]
Can you also remove your changes on the LegacyPhpDumper? Thanks :)

**Comment by Crease29** [comment]
Sorry, i have completely messed up this branch and created a new PR: https://github.com/shopware/shopware/pull/1830
Excuse the circumstances.

**Pull request closed without merging**
