### PR TITLE
Fix shop duplication bug

### PR DESCRIPTION
**Pull request by andrewisplinghoff**
This is a new pull request for the shop duplication bug previously discussed here: https://github.com/shopware/shopware/pull/169

The proposed fix is based on @hlohaus changes as mentioned in
https://github.com/shopware/shopware/pull/169#issuecomment-49440259

The changes to engine/Shopware/Plugins/Default/Core/Router/Bootstrap.php are necessary so that real subshops created with the SwagMultiShop plugin still work after the fix. Without these changes, the user is always redirected to the main shop. I successfully tested that language subshops still work without these lines.

/cc @jhit

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks @andrewisplinghoff. Can you figure out why the tests are failing?

**Comment by samuelvogel** [comment]
We just created a new PR based on Shopware 5.1 for this: https://github.com/shopware/shopware/pull/437

**Comment by bcremer** [comment]
Closed in favor of https://github.com/shopware/shopware/pull/437.

**Comment by samuelvogel** [comment]
Sorry for rebasing this on `5.1` while the PR was against the `5.0` branch which can't be changed :wink:

**Pull request closed without merging**
