### PR TITLE
Remove customer id limitation from shipping address (SW5.7.3 & B2B-Suite)

### PR DESCRIPTION
**Pull request by Nevay**
### 1. Why is this change necessary?
B2B-Suite contact ids differ from the user_id stored in the address (debtor id).

### 2. What does this change do, exactly?
Remove check for matching customer id, added in [SW-25778](https://github.com/shopware/shopware/commit/ad174f77d3881bde501dbb6e0d71a0de4b3162ee#diff-ccef450af51163136d58b2a86d0624de543261e45ce16710130d81430b150ba4R4349-R4351).

### 3. Describe each step to reproduce the issue or behaviour.
Install B2B-Suite on SW5.7.3 and call `sAdmin::sGetUserData()` on a contact with default shipping address.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @Nevay 

thanks for your contribution :slightly_smiling_face: 

Which version of the B2B-Suite are you using? This should be fixed with 3.1.1

**Comment by Nevay** [comment]
We are using 3.1.1, I currently can't reproduce the problem with a clean installation. I will provide more details if I can narrow it down (we get `$shippingAddress->getCustomer()->getId() = 0` for the initial login attempt with our setup, without `CustomerSubscriber::postLoad()` we get the debtor userId as expected).

The postLoad id-rewrite fix doesn't seem to be the correct solution as it corrupts the doctrine entity map and may lead to problems depending on the order in which entities are loaded / used (loading the debtor customer entity afterwards loads the broken entity with contact id). Adding a PreDispatch_Frontend subscriber that calls `Shopware()->Modules()->Admin()->sGetUserData()` showcases this problem (see below).

---

Shopware #f5b4c9b, setup via `make init`
Plugins:
\- Cron
\- B2B-Suite 3.1.1
\- TestPlugin

```php
<?php
namespace TestPlugin;

class TestPlugin extends \Shopware\Components\Plugin {

    public static function getSubscribedEvents() {
        return ['Enlight_Controller_Action_PreDispatch_Frontend' => 'loadUserData'];
    }

    public function loadUserData(): void {
        Shopware()->Modules()->Admin()->sGetUserData();
    }
}
```

Steps:
\- Mark test@example.com as debtor.
\- Login as debtor, add role and contact.
\- Login as contact.

<details><summary>Error after login as contact</summary>

```
Fatal error: Uncaught Error: Call to a member function getAttribute() on null in custom/plugins/SwagB2bPlugin/components/Dashboard/Bridge/EmotionRepository.php:83
Stack trace:
#0 custom/plugins/SwagB2bPlugin/components/Dashboard/Bridge/EmotionRepository.php(67): Shopware\B2B\Dashboard\Bridge\EmotionRepository->getEmotionFromCustomerGroup()
#1 custom/plugins/SwagB2bPlugin/components/Dashboard/Bridge/EmotionRepository.php(108): Shopware\B2B\Dashboard\Bridge\EmotionRepository->getEmotionId()
#2 custom/plugins/SwagB2bPlugin/components/Dashboard/Frontend/DashboardController.php(51): Shopware\B2B\Dashboard\Bridge\EmotionRepository->fetchEmotion()
#3 custom/plugins/SwagB2bPlugin/Extension/FrontendControllerProxy.php(47): Shopware\B2B\Dashboard\Frontend\DashboardController->indexAction()
#4 engine/Library/Enlight/Controller/Action.php(182): SwagB2bPlugin\Extension\FrontendControllerProxy->__call()
#5 custom/plugins/SwagB2bPlugin/Extension/FrontendControllerProxy.php(30): Enlight_Controller_Action->dispatch()
#6 custom/plugins/SwagB2bPlugin/Extension/RoutingInterceptor.php(15): SwagB2bPlugin\Extension\FrontendControllerProxy->SwagB2bPlugin\Extension\{closure}()
#7 custom/plugins/SwagB2bPlugin/Extension/FrontendControllerProxy.php(31): SwagB2bPlugin\Extension\RoutingInterceptor->interceptException()
#8 engine/Library/Enlight/Controller/Dispatcher/Default.php(461): SwagB2bPlugin\Extension\FrontendControllerProxy->dispatch()
#9 engine/Library/Enlight/Controller/Front.php(225): Enlight_Controller_Dispatcher_Default->dispatch()
#10 engine/Shopware/Kernel.php(197): Enlight_Controller_Front->dispatch()
#11 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): Shopware\Kernel->handle()
#12 vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle()
#13 engine/Shopware/Components/HttpCache/AppCache.php(262): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward()
#14 vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Shopware\Components\HttpCache\AppCache->forward()
#15 vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch()
#16 engine/Shopware/Components/HttpCache/AppCache.php(189): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup()
#17 vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Shopware\Components\HttpCache\AppCache->lookup()
#18 engine/Shopware/Components/HttpCache/AppCache.php(114): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle()
#19 shopware.php(122): Shopware\Components\HttpCache\AppCache->handle()
#20 {main} thrown in custom/plugins/SwagB2bPlugin/components/Dashboard/Bridge/EmotionRepository.php on line 83
```
</details>

**Comment by mitelg** [comment]
hey @Nevay 

we discussed this again in the team and we decided to implement your PR and fix the B2B suite afterwards.

**Comment by mitelg** [comment]
thanks for your contribution @Nevay :+1: :tada: :blue_heart:

don't be confused, we merged it on the next branch, which will be merged back to the main branch in a few days

**Pull request closed without merging**
