### PR TITLE
Account Sidebar - Add .is--active when in note-controller

### PR DESCRIPTION
**Pull request by screeny05**
I don't see a reason not to add the is--active class for the notes-entry of the account-sidebar.

### CODE REVIEW

**Comment by stevehempel** [comment]
I don´t see a reason for adding this class at this point. I tried and nothing changed. What should it do?

**Comment by screeny05** [comment]
To clarify:

The Account-Sidebar contains the entry `Wishlist`. The problem is, that this entry doesn't get the `is--active`-class indicating, that the current page is the entry. I don't know, why this hasn't been fixed before, but this pull-request tries to do this. It adds the `is--active`-class to the `wishlist`-entry, when the current active controller is the `note`-controller.

Infos according to `CONTRIBUTING.md`:
- This won't break stuff
- UPGRADE.md changed

**Comment by janbuecker** [comment]
Hi @screeny05 and thanks for your PR.

Please rebase your PR and resolve the conflicts. I'll schedule your PR afterwards. :)

**Comment by screeny05** [comment]
done

**Comment by janbuecker** [comment]
Thank you, I've scheduled your PR.

**Comment by janbuecker** [comment]
Thanks, merged with f228a802f784a9f60583c518a6b37fece58b24c5.

**Pull request closed without merging**
