### PR TITLE
Fixed W3C Error - div as ul child

### PR DESCRIPTION
**Pull request by iLuHa91**
W3C Error "Element div not allowed as child of element ul" fixed.

### CODE REVIEW

**Comment by bcremer** [comment]
@shopware/shopware-webdev can you please review?

**Comment by klarstil** [comment]
@iLuHa91 Thanks for your contribution. We have to double check your changes cause it can break the layout of the mobile switches.

@bcremer We should import this as a new ticket.

**Comment by iLuHa91** [comment]
Have fixed this in my custom Theme like that. Nothing is broken ;-) Just for your information.
Would be nice if this would be fixed in core.

**Comment by Phil23** [comment]
Thank you for your work.
Changes will be released with SW 5.1.4

**Comment by iLuHa91** [comment]
I'm missing this change in Shopware 5.2.X and also in Shopware 5.3.X

**Pull request closed without merging**
