### PR TITLE
Accept urls with and without trailing slash

### PR DESCRIPTION
**Pull request by ahmad-saad**
### **Why is it necessary?**
if the url saved in s_core_rewrite_urls table with trailing slash for example 'womens/' then if I call it with 'womens' without slash it not find the page and redirect me to the homepage.

and the problem that the code generate the urls sometimes with trailing slash (like the categories) and sometimes without trailing slash (like the products or static pages).

so I can't do anything with .htacess to add or remove the trailing slash from the urls.

### **What does it improve?**
after this change the code will search for the page name und not the exact value with trailing slash. and that will be more senses.

### **Does it have side effects?**
No

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       |  no
| Tests pass?      |  yes
| Related tickets? | [SW-17514](https://issues.shopware.com/issues/SW-17514)
| How to test?     | simply call the Shopware demo page and then remove or add the trailing slash for example : http://www.shopwaredemo.de/beach-relax/fashion/women/ and http://www.shopwaredemo.de/beach-relax/fashion/women

### CODE REVIEW

**Comment by ahmad-saad** [comment]
Hallo @shopwareBot ,
thank's for accepting this pull request.

but I have Q, why the check ist failed. my pull request always failed with php7.1 check.

can you tell me why this happened.

thank's,
Ahamd

**Comment by bcremer** [comment]
@ahmad-saad thanks for your contribution. The failing test is not related to your PR. Restarted the build and now it's green again :)

**Comment by janbuecker** [comment]
Sorry, but this PR has been reverted because of potential duplicate content.

**Comment by dnoegel** [comment]
@janbuecker Shouldn't it actually do a proper redirect to the canonical URL?

**Comment by janbuecker** [comment]
Unfortunately, is doesn't. In addition, there are missing canonical URLs on some pages e.g. forms.

So, the proposed change would introduce more problems than it solves.

**Comment by ahmad-saad** [comment]
so , I think the best solution is use the same way to create the rewrite urls ( with or without trailing slash).
then use .htaccess to redirect to the correct url format ( with or without).

**Pull request closed without merging**
