### PR TITLE
Added media optimizer overview to systeminfo

### PR DESCRIPTION
**Pull request by shyim**
## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | Its needed to check the optimizers on the web enviroment |
| BC breaks?              | no |
| Tests exists & pass?    | yes |
| Related tickets?        |  |
| How to test?            | Open the module systeminfo and go to tab "Media Optimizer" |
| Requirements met?       | Yes |

Screenshot :)

Overview

### CODE REVIEW

**Comment by shyim** [comment]
And whats about images which are uploaded in backend using media manager? They won't be optimized automatically and currently is it not possible to check if any optimizer is available in backend

**Comment by shyim** [comment]
any answer? :D

**Comment by tinect** [comment]
I've to agree to shyim.
There is no possibility to check for runnable optimizers in backend. Just to make some transparent informations for default shop-user.
All functions should be accessible from backend, if they could show informations about the environment in an easy way.

And regarding the "thumbs up emoji" it isn't just a "personal intent".

**Comment by tinect** [comment]
@shopwareBot 
We'd like to push this thread ;-)

**Comment by shyim** [comment]
@shopwareBot Ping.....

**Comment by shyim** [comment]
@shopwareBot ping 🙄

**Comment by tinect** [comment]
@shopwareBot ping

**Pull request closed without merging**
