### PR TITLE
Add Filter event to backend variant generation

### PR DESCRIPTION
**Pull request by larsbo**
### 1. Why is this change necessary?

Without the event it is not easy to change variant details during backend generation programmatically.

### 2. What does this change do, exactly?

This PR adds a new filter event `Shopware_Controllers_Article_CreateConfiguratorVariants_FilterData` which allows the modification of article variants during backend generation.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by larsbo** [comment]
@shopwareBot The use case is to set a unique value to each generated variant, e.g. in our case an unique EAN number.

**Comment by larsbo** [comment]
sounds legit 😉 I'll update my PR!

**Comment by larsbo** [comment]
@shopwareBot Using the `$data` array instead of the model has the drawback that there is no possibility to check if the variant is newly generated or not. 
When using the `Detail` model you can check if `$detail->getId()` is zero but inside the `$data` array every variant got the `id` copied from the main detail. This could be solved by resetting the id inside `prepareVariantData()`. I updated my PR with that change and hope this is no breaking change 😃

**Comment by larsbo** [comment]
That's also fine. I updated the PR.

**Comment by larsbo** [comment]
@shopwareBot the changelog entry of the PR should be moved from 5.5.0 to 5.5.2 😉

**Comment by shyim** [comment]
@larsbo We are collecting new entries / changes for UPGRADE.md and changes that all in one commit before a release happens. That save us time and makes the work with pull requests faster 😊 .

So we have it on the list to update that 😉

**Comment by larsbo** [comment]
alright, makes sense 😄

**Pull request closed without merging**
