### PR TITLE
[FIX] Possibility to set a non ssl/tls mailer for the newsletter

### PR DESCRIPTION
**Pull request by wildi1**
## Description
Please describe your pull request:
* When the default mailer in shopware is ssl/tls, then it is not possible to set an non ssl/tls mailer for the newsletter, because the setting ssl => null is getting always overwritten. 0 or an emtpy string is also not possible because of the Zend_Mail_Protocol_Smtp
* You can set a non ssl/tls newsletter mailer, even the default mailer is ssl/tls?
* No?

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | yes
| Tests pass?      | yes
| Related tickets? | No
| How to test?     | Try to setup a non ssl/tls newsletter mailer when the default mailer is ssl/tls

### CODE REVIEW

**Comment by klarstil** [comment]
Hey @wildi1,
thanks for your pull request. Would you be so kind and change the target version to the 5.3 version (https://github.com/shopware/shopware/tree/5.3)?
Best regards,
klarstil

**Comment by wildi1** [comment]
Hey @klarstil ,
I have changed the target version to 5.3.
Best regards,
wildi1

**Comment by mitelg** [comment]
hey @wildi1 
now you have to rebase your branch on base of 5.3 of course :wink:

**Comment by wildi1** [comment]
hi @mitelg ,
sorry but I have not the most experience with such things like rebase etc. and no Idea how this works :-). Can you explain it short ?

**Comment by mitelg** [comment]
hey @wildi1 
maybe the best thing for you would be to create a new PR. because explaining it in "short" over github won't work :wink:

**Comment by wildi1** [comment]
hey @mitelg 
here is my new PR:
https://github.com/shopware/shopware/pull/894

**Pull request closed without merging**
