### PR TITLE
Fix priority in event manager

### PR DESCRIPTION
**Pull request by hlohaus**
### 1. Why is this change necessary?

If you have many plugins the priority isn't right... 

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by hlohaus** [comment]
i added a test, wich fail without my change.

**Comment by soebbing** [comment]
Since this is a very important and basic functionality of Shopware, we'll need some more tests, eg. that adding events without any priority are kept in order, that multiple events WITH priorities are correctly sorted and a combination of both.

Also, to be able to add this functionality without breaking existing installations, it would be great if this new behavior could be activated by a config switch for the moment. That way users could test it in a save way before we activate it by default in a future version, similar to what we're currently doing with the order plugins are activated.

**Comment by hlohaus** [comment]
I added a config switch and improved the tests.

**Comment by hlohaus** [comment]
I added deprecations for #2151.
Also i fixed the removing of plugin handler.

**Comment by shyim** [comment]
Hey @hlohaus,
when we do something on our Event Manager, we want to switch then to Symfony Events (#2151). So I will close this Pull Request then
Anyway thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
