### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by JoshuaBehrens**
### 1. Why is this change necessary?
Loading dependencies in a plugin that require more recent versions of it are blocked by the existing ones required in a shopware composer project. Having these in a non-composer installation the plugin would just break.

### 2. What does this change do, exactly?
Remove dependencies that seem not to be used anymore. (regarding the usage of the namespace)

### 3. Describe each step to reproduce the issue or behaviour.
1. Require `php-http/client-common ^2.0` in plugin
2. Composer breaks

### 4. Which documentation changes (if any) need to be made because of this PR?
A removal hint of dependencies needs to be added so if a plugin was using a not-used dependency it knows it should just use Guzzle.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Hey @JoshuaBehrens,
we cannot drop packaged libraries in a patch release. These dependencies are already removed in 5.7 branch.

**Comment by JoshuaBehrens** [comment]
@shyim always faster than the tests 😁 I get it. Not fixing my issue though 😖

**Comment by shyim** [comment]
I am closing this then because we have already removed that library in Shopware 5.7

Maybe a solution could be to prefix your dependencies with php scooper
https://github.com/humbug/php-scoper

**Comment by JoshuaBehrens** [comment]
Thanks for knowing this project by your heart. I am just unhappy that this didn't happen earlier 😊

**Pull request closed without merging**
