### PR TITLE
fix: Ensure compatibility with newer libxml2 versions on linux distributions

### PR DESCRIPTION
**Pull request by mitelg**
Changed plugin.xsd to ensure compatibility with newer libxml2 versions. 

Fixes
> complex type 'pluginType': The content model is not determinist

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Comment by sneakyvv** [comment]
Same thing happens with [config.xsd](https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd)

> Unable to parse file ".../vendor/.../src/Resources/config/config.xml". Message: [ERROR 3070] complex type 'input-field': The content model is not determinist. (in in_memory_buffer - line 31, column 0)

config.xml refers to config.xsd.

**Comment by mitelg** [comment]
hey @sneakyvv 
the issue is already fixed for Shopware 6

**Comment by sneakyvv** [comment]
> the issue is already fixed for Shopware 6

No, it still is present in https://raw.githubusercontent.com/shopware/platform/master/src/Core/System/SystemConfig/Schema/config.xsd

and I'm using Shopware 6.5.1.1

**Comment by mitelg** [comment]
then please create an issue in the SW6 project and do not hijack a SW5 PR :slightly_smiling_face:

**Review by DennisGarding — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Pull request merged**
