### PR TITLE
typos in method name and phpdoc

### PR DESCRIPTION
**Pull request by SvenHerrmann**

### CODE REVIEW

**Comment by bcremer** [comment]
`assertVersionGreaterThen()` is already deprecated in favor of `assertMinimumVersion()`.
We did not alone to fix the than/then-typo, but also to be more semantic correct. 

`assertVersionGreaterThen()` should have been named `assertVersionEqualsOrGreaterThan()` from the beginning.

I cannot see a need for another alias to the new `assertMinimumVersion()`.

Any reasons why the new method should be introduced?

**Comment by tiagojsag** [comment]
We should, nonetheless, fix the typo in the `deprecated` tag, as to make the deprecation more visible (ie. PHPStorm automatically highlights deprecated methods, which is not currently true for this method due to the typo). 

As for the wrapper method, I agree with @bcremer that we should not introduce it. The typo problem will be fixed once we remove the deprecated method.

**Comment by SvenHerrmann** [comment]
Ok, you're right. But at least the typo in phpdoc should be fixed, so one can see in PhpStorm, that the method is deprecated.

**Comment by bcremer** [comment]
Thank you @SvenHerrmann. I included your commit into the 5.1 branch.

**Pull request closed without merging**
