### PR TITLE
[Papercut][SW-12745] Fix voucher wrong enddate

### PR DESCRIPTION
**Pull request by TobiasWilming**
This PR now compares the voucher validdate with the Date instad of the datetime from today so that the last day is now included to the days that you can use the voucher.

| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? | https://issues.shopware.com/#/issues/SW-12745 https://issues.shopware.com/#/issues/SW-15604 |
| How to test? | Set the valid_from date to something and the valit_to time of a voucher to the current date and check if you can use the voucher in the frontend. You should also make a check if its available on the next date at 0:00 . |

### CODE REVIEW

**Comment by htkassner** [comment]
I think this is even more confusing the user, because in the backend you configure a till date. As voucher user I would suggest my voucher is still usable on the day it ends and not the day before.

**Comment by TobiasWilming** [comment]
I think I described it wrong. With this PR if you configure a till date it is now possible to use that voucher until the day ends. Without the PR it isnt possible to use it at the last (configured) day

**Review by janbuecker — CHANGES_REQUESTED** [review]
There are more places where the query needs to be updated. f.e.
- engine/Shopware/Plugins/Default/Core/CronBirthday/Bootstrap.php
- engine/Shopware/Controllers/Backend/Newsletter.php
- engine/Shopware/Controllers/Backend/CanceledOrder.php
- engine/Shopware/Components/Document.php

Please search the whole codebase to find all places where it needs to be fixed.

**Comment by TobiasWilming** [comment]
Updated it.

**Pull request merged**
