### PR TITLE
Added attributes to cms page

### PR DESCRIPTION
**Pull request by shyim**
## Description
Please describe your pull request:
* What does it improve?
Add attributes to $sCustomPage
* Does it have side effects?
Nope

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | If this PR fixes an existing [Issue](https://issues.shopware.com) ticket, please add its complete issue URL.
| How to test?     | Show variables of cms page

### CODE REVIEW

**Comment by soebbing** [comment]
Hi shyim! Could you name a use case for this PR and a short description of how to test the functionality?

**Comment by alea123** [comment]
usecase 1: more flexibility in templates for custom pages when accessing attributes in frontend. eg. robots-tag follow/nofollow/index/noindex... this is not possible atm,
usecase 2: plugins which add custom attributes (freetextfields/freitextfelder) to custom pages could work 100%
usecase 3: accessing attributes in frontend would achieve more seo-compatibility

**Comment by t2oh4e** [comment]
Actually it's pretty useless for people who use the (not so) new posibiltiy do add their own attribute via backend if they can't use them in the frontend templates. That contradicts the concept of being able to add your own attributes without building plugins. All attributes should be accessible in the frontend everywhere where the entity they belong to is used. So thanks @shyim for adding them in multiple places.

**Comment by janbuecker** [comment]
Has been merged with 6d4dd8fa2989e5c1c812fd4955bc533b3a594492.

**Pull request closed without merging**
