### PR TITLE
Added command to refresh topseller

### PR DESCRIPTION
**Pull request by FiveDigital**
### 1. Why is this change necessary?
Topseller can currently only be refreshed via backend or cron. 

### 2. What does this change do, exactly?
Adds a console command to refresh the topseller index.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by FiveDigital** [comment]
Please also note that there is some kind of misbehaviour using the cron strategy because of this:

```
        if (!($this->isTopSellerActivated()) || $strategy !== self::AGGREGATE_STRATEGY_CRON_JOB) {
            return true;
        }
```

If the topsellers are not shown in the frontend the index is not generated by the cron. If the index is not generated the `sales` are not put into the elasticsearch index ...

**Comment by larsbo** [comment]
@FiveDigital the wrong frontend dependency has been fixed with Shopware 5.5.3 (https://github.com/shopware/shopware/pull/1262) 😃

**Comment by FiveDigital** [comment]
Ah nice - the PR with the birthday party 😬 👍

**Comment by shyim** [comment]
Code Style check fails 😉

**Comment by FiveDigital** [comment]
It should pass now.

**Pull request closed without merging**
