### PR TITLE
[FEATURE] Added new jsbase theme filled only with javascript and cha…

### PR DESCRIPTION
**Pull request by wolv-dev**
…nged extension of responsive theme, removed js from responsive theme

## Description
Added new Theme including only the javascript files. This enhances the process of creating new themes based on responsive theme, cause you don't need to copy and paste all the JS from one theme to another.
It increases maintainability of custom themes, cause the JS will be updated from you (Shopware) and no need to recopy and paste the updates JS in own custom theme.

I also updated the karma/jasmine tests to work with the new theme and added the dev dependencies for karma, jasmine, phantomJS, ... 

Branch was: https://github.com/shopware/shopware/pull/980
Now for version 5.3

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | No related ticket
| How to test?     | npm install in new BaseJs Theme, grunt and npm run test

### CODE REVIEW

**Comment by mitelg** [comment]
@shopwareBot there is already a ticket for that. I updated the referring links
https://issues.shopware.com/issues/SW-17845.

**Comment by mitelg** [comment]
@wolv-dev thanks for updating your contribution :+1: 
the ticket seems to be planned for the next sprint :blush:

**Comment by jenskueper** [comment]
@wolv-dev Thank you for the PR! I startet testing it but received an error message in the frontend. Would be great if you can take a look at it:

bildschirmfoto 2017-10-26 um 10 35 04

**Comment by wolv-dev** [comment]
@jenskueper Thanks, fixed it. And changed to 5.4

**Comment by wolv-dev** [comment]
Something similar was added with version 5.4. Pull Request closed.

**Pull request closed without merging**
