### PR TITLE
Refactored xml parser + tests

### PR DESCRIPTION
**Pull request by nlubisch**
Reopened as the topic arised in Gitter.im.
Old PR: #954
Ticket: https://issues.shopware.com/issues/SW-17837

## Description
* Why is it necessary?
Refactored xml readers because every programmer does his own thing.
There were some redundant functions which i moved to a abstract base class.
All readers are now unified and 100% tested.

screenshot from 2017-02-05 19-37-41
screenshot from 2017-02-05 19-38-09

* What does it improve?
It does improve code, tests and xsd files.

**BC breaks?**
-> config.xsd
storeType has changed. PHP got removed due to when inserting an php array as CDATA you have to eval it to get the data and that is IMO a security issue.
There is now an explicit way to declare which type of store it is.

-> plugin.xsd
pluginName-attribute in "requiredPlugin" is now required.
complexType "scope" got removed because its not used.

**Tests pass?**
No, but only non related tests fail.

### CODE REVIEW

**Comment by shyim** [comment]
Code-Style check fails

**Comment by nlubisch** [comment]
Sure, i can. Give me some time :)

**Comment by nlubisch** [comment]
Removed the misc stuff and opening a new PR with them in a minute.
I'm looking for the failing test this evening.

**Comment by nlubisch** [comment]
The test succeeds locally. Don't see the problem here :(

**Comment by shyim** [comment]
Same problem also local https://dpaste.de/i0yR

**Pull request closed without merging**
