### PR TITLE
Implement is new condition for product streams

### PR DESCRIPTION
**Pull request by FiveDigital**
We need this for one of our customers and I think it will fit in the core.

### CODE REVIEW

**Comment by bcremer** [comment]
Hi @FiveDigital, thank you for this PR. At a first glance it looks very promising.

This PR will be tracked with Ticket [SW-13964](https://issues.shopware.com/#/issues/SW-13964) and is currently scheduled for our next sprint that goes from Feb. 9 to Feb. 19.

**Comment by FiveDigital** [comment]
Thanks :+1: Let me know if there's anything to fix.

**Comment by FiveDigital** [comment]
Now there are two tickets for this PR:

https://issues.shopware.com/#/issues/SW-13929
https://issues.shopware.com/#/issues/SW-13964

**Comment by bcremer** [comment]
Good catch, the bot created another one. I removed the duplicate Ticket and updated my comment form yesterday.

**Comment by janbuecker** [comment]
Fixed & merged with commit 88c8db1.

Thanks you @FiveDigital.

**Pull request closed without merging**
