### PR TITLE
change uses of $value in getBasketArticles function to $getArticles

### PR DESCRIPTION
**Pull request by teiling88**
with the event "Shopware_Modules_Basket_GetBasket_FilterItemStart" i can't change the modus for a specific entry of the array $getArticles.

In our case, we use this event to prevent a voucher update.

### CODE REVIEW

**Comment by dnoegel** [comment]
Looks good; the only thing one might discuss is the unused `$value` variable that actually should not be used for extensibility reasons (as this PR shows). So an `foreach(array_keys($getArticles) as $key) { }` or something like that might also do the trick.

**Comment by teiling88** [comment]
thanks for your feedback - i will fix it

**Comment by teiling88** [comment]
the fixed version as promised :-)

**Comment by bcremer** [comment]
@teiling88 Thank you for getting involved  :+1:

**Pull request merged**
