### PR TITLE
SSL fix from http to https for schema.org and facebook.com

### PR DESCRIPTION
**Pull request by christopherholst**
If a resource is available over SSL, then always use the https:// URI.

### 1. Why is this change necessary?
Loads page resources using protocol relative URIs
Loading a resource using protocol relative URIs allow it to be requested over HTTP and opens the door for Man-on-the-side attacks. If a resource is available over SSL, then always use the https:// URI.

### 2. What does this change do, exactly?
change from http to https urls where https urls are available

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by tinect** [comment]
Just to be sure: There isn't any request to schema.org, so this change is just for style :-)

**Comment by mitelg** [comment]
@tinect and totally useless for schema.org? :thinking:

**Comment by larsbo** [comment]
@mitelg your buddy Hendrik checked it in a previous PR: https://github.com/shopware/shopware/pull/2300#issuecomment-575067424

**Comment by tinect** [comment]
> @tinect and totally useless for schema.org? 🤔

@mitelg no, it's just typo ;-) Can be merged. I just wanted to make clear changing schema.org-declarations hasn't anything to do with security.

**Comment by soebbing** [comment]
There are two possible benefits I see in this PR, both rather negligible: For one, other developers seeing the reference in the source use https when visiting the schema.org-reference. And also there won't be another PR in the foreseeable future regarding this change/. :)

**Comment by soebbing** [comment]
Hi @snHolst, thanks for pulling through and change the protocol everywhere! 💙

**Pull request closed without merging**
