### PR TITLE
[Papercut][SW-12659] - escape quotes in form values

### PR DESCRIPTION
**Pull request by teiling88**
## Description

fix broken view if user fill an input field with a double quote

Replace double quotes with single quotes if it was possible
Add missing @throws tags
some very small improvements

| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? | https://issues.shopware.com/#/issues/SW-12659 |
| How to test? | Fill a form with a double quote and submit it |

### CODE REVIEW

**Comment by bcremer** [comment]
@teiling88 Thanks for you contribution. It's hard to review your change when you mix functional changes with code stlye fixes. Can you please split up your PR into two separate commits. One for the functional change/bugfix and one for the coding style changes.

Thank you.

**Comment by teiling88** [comment]
no problem - is splitted :-)

**Comment by janbuecker** [comment]
@teiling88 please add this fix for `text2` fields too.

**Comment by teiling88** [comment]
done - i added the {/literal} check too for text2 fields.

**Comment by janbuecker** [comment]
Looks good to me now. Thanks 👍

**Pull request merged**
