### PR TITLE
add a new snippet for decimal precision of article price

### PR DESCRIPTION
**Pull request by mnaczenski**
### 1. Why is this change necessary?
When using net prices it would be helpful to be able to add prices with a higher decimal precision than two. Especially when you want to get a rounded gross-price.

### 2. What does this change do, exactly?
Change the decimal precision of the price column to a snippet, so you can change the precision in the backend.

### 3. Describe each step to reproduce the issue or behaviour.
Try to add 4,1256 as net price to an article

### 6. Checklist

- [ x] I have written tests and verified that they fail without my change
- [ x] I have squashed any insignificant commits
- [ x] This change has comments for package types, values, functions, and non-obvious lines of code
- [ x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
why didn't you add these new snippets to the ini files?

**Comment by mnaczenski** [comment]
@mitelg done

**Comment by mitelg** [comment]
@mnaczenski you forgot the german "translation". also the value in the ini file defers from the value in the javascript files

**Comment by mnaczenski** [comment]
@mitelg thank you for the hint.
I didn't recognize that there are two languages in the ini file.

**Pull request closed without merging**
