### PR TITLE
Fix for #SW-11616 - Click area on article detail page

### PR DESCRIPTION
**Pull request by OliverZachau**
The click area for the lightbox is based on the image width and height. When the width and height is smaller then the wrapper class itself the result is a click area which is not directly placed on top of the image but aligned to the left. Making the click on the image not getting recognized.

By changing the width of the click area to auto the area has the needed width to make sure that every click is getting recognized.

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks for your pull request.

Please have a look into our [Contribution Guidlines](https://github.com/shopware/shopware/blob/5.0/CONTRIBUTING.md). 

The pull request should be in English. Also please remove the imgur.com link from the commit message since the link may be no longer valid in the feature.

**Comment by bcremer** [comment]
@shopware/shopware-webdev Can you please confirm the bug and test the provided fix.

**Comment by klarstil** [comment]
Alright, I checked out the pull request and reviewed it. I'm sorry, but the modification doesn't work as intended. The mousetrap has `position: absolute` and no content, therefore the mousetrap would have a width of `0px`. The other issue I spotted was the arguments in the string. The placeholder for the first argument in the string should be `%0` but in the pull request the first placeholder is `%1`, which results in a broken `top` and  `left` values:

Chrome DevTools

I've marked the pull request as "declined". @OliverZachau, you still have the ability to change the pull request and fix the issues.

**Comment by OliverZachau** [comment]
I fixed the errors and provided a new fix that should now work as intended.

Thank you for the feedback!

**Comment by klarstil** [comment]
@OliverZachau Thanks for the quick response. The changes looking good and the code is working as intended.

@bcremer The pull requests looks good :) You can merge it

**Comment by bcremer** [comment]
Merged in commit https://github.com/shopware/shopware/commit/ea40624f7bf74a3ab81b6dcdf0c36beed545fd10.

Thanks for your help.

**Pull request closed without merging**
