### PR TITLE
Updated .gitignore for media files

### PR DESCRIPTION
**Pull request by b3nl**
Enables the versioning of "fixed" user files like a favicon.ico and preserves the internal git files.

### CODE REVIEW

**Comment by jhofm** [comment]
also i just saw that officially "An Apache web server" is part of the sw5 requirements. so i guess a .htaccess file is valid. ^^

**Comment by janbuecker** [comment]
Thanks for your contribution @b3nl.

We decided to address this issue from the ground up and created a new ticket for this. You can up-vote this ticket here: https://issues.shopware.com/issues/SW-17217

**Comment by bcremer** [comment]
Fixed with commit https://github.com/shopware/shopware/commit/256e28b30b33b097b5c038b36276a6215b1c8867.

Thanks for your feedback.

**Comment by b3nl** [comment]
what a bad piece of english months ago ;) Thx for the work!

**Pull request closed without merging**
