### PR TITLE
Shopware powered by Unicorns

### PR DESCRIPTION
**Pull request by shyim**
## Description
Please describe your pull request:
* Why is it necessary?
Because unicorns :3
* What does it improve?
Replaces global boring Shopware() method with magic 🦄(). 
* Does it have side effects?
Nope

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | 🦄
| Tests pass?      | yes
| Related tickets? | https://issues.shopware.com/issues/SW-UNICORN
| How to test?     | Try the unicorn power with 🦄()->Db()->fetchAll('SELECT * FROM s_user');

### CODE REVIEW

**Comment by sebastien-fauvel** [comment]
🦄
  :1st_place_medal:

**Comment by t2oh4e** [comment]
All hail the magic 🦄 !

**Comment by mitelg** [comment]
Hey @shyim 
thanks for your PR :+1: 
again an awesome contribution of one of our most valuable community members :smiley: :tada: 

BUT! 
as I am not that into unicorns I would very appreciate if you could change the unicorn in something that is more similar to Shopware. Something like the beer :beer: and/or the blue heart :blue_heart: emoji 

Best regards from Schöppingen
Michael Telgmann

**Comment by dnoegel** [comment]
Awesome 😍

**Comment by bcremer** [comment]
I like the fact that all unit tests are still passing https://travis-ci.org/shopware/shopware/jobs/217371806#L859 :1st_place_medal:

**Comment by ndzoesch** [comment]
@shyim thank you for your continued effort. I'm really sad to tell you we have to decline your pull request. A third party, which is certainly not THE SECRET SOCIETY OF THE UNICORNS, talked to us. Obviously your PR harms the rights of this unnamed third party and the rights of all living unicorns. Again, thanks for your effort.

**Pull request closed without merging**
