### PR TITLE
Shopware\Models\Customer\Billing does not expose underlying relationship to doctrine

### PR DESCRIPTION
**Pull request by shredding**
The billing class has an imprecise doctrine annotation mapping that hides the underlying relationship of the data structure from doctrine; namely, access to the `countryId` is of no (or little) use for the ORM Framework. 

The attached pull request fixes that. I'd recommend to flag the `countryId` and it's getter/setter methods as deprecated as well.

_Example usecase_

Adding the country to the customer listing in the backend requires manipulating the query builder and bypassing the doctrine infrastructure would lead to nasty and overcomplicated workarounds.

With the attached fix it would be as easy as:

``` php
public function afterGetListQueryBuilder(Enlight_Hook_HookArgs $arguments)
{
    /** @var \Shopware\Components\Model\QueryBuilder $builder */
    $builder = $arguments->getReturn();
    $builder->leftJoin('billing.country', 'country');
    $builder->addSelect('country.name as countryname');
    $arguments->setReturn($builder);
}
```

### CODE REVIEW

**Comment by dnoegel** [comment]
Hi, 
thanks for your pull request, I'll move it to our internal repo tomorrow.

**Comment by dnoegel** [comment]
Hi,

it is in CR now.

**Comment by iparker** [comment]
This modifications raises an error in the customer-import (just when importing new customers! 

Error message: Errors: Error in line 7: SQLSTATE[42000]: Syntax error or access violation: 1110 Column 'countryID' specified twice Error in line 8: The EntityManager is closed. Error in line 9: The EntityManager is closed. Error in line 10: The EntityManager is closed. Error in line 11: The EntityManager is closed. Error in line 12: The EntityManager is closed. Error in line 13: The EntityManager is closed. Error in line 14: The EntityManager is closed. Error in line 15: The EntityManager is closed. Error in line 16: The EntityManager is closed. Error in line 17: The EntityManager is closed. Error in line 18: The EntityManager is closed. Error in line 19: The EntityManager is closed. Error in line 20: The EntityManager is closed. Error in line 21: The EntityManager is closed. Error in line 22: The EntityManager is closed. Error in line 23: The EntityManager is closed. Error in line 24: The EntityManager is closed. Error in line 25: The EntityManager is closed. Error in line 26: The EntityManager is closed. Error in line 27: The EntityManager is closed. Error in line 28: The EntityManager is closed. Error in line 29: The EntityManager is closed. Error in line 30: The EntityManager is closed. Error in line 31: The EntityManager is closed. Error in line 32: The EntityManager is closed. Error in line 33: The EntityManager is closed. Error in line 34: The EntityManager is closed. Error in line 35: The EntityManager is closed. Error in line 36: The EntityManager is closed. Error in line 37: The EntityManager is closed. Error in line 38: The EntityManager is closed. Error in line 39: The EntityManager is closed. Error in line 40: The EntityManager is closed. Error in line 41: The EntityManager is closed. Error in line 42: The EntityManager is closed. Error in line 43: The EntityManager is closed. Error in line 44: The EntityManager is closed. Error in line 45: The EntityManager is closed. Error in line 46: The EntityManager is closed. Error in line 47: The EntityManager is closed. Error in line 48: The EntityManager is closed. Error in line 49: The EntityManager is closed. Error in line 50: The EntityManager is closed. Error in line 51: The EntityManager is closed. Error in line 52: The EntityManager is closed. Error in line 53: The EntityManager is closed. Error in line 54: The EntityManager is closed. Error in line 55: The EntityManager is closed. Error in line 56: The EntityManager is closed. Error in line 57: The EntityManager is closed. Error in line 58: The EntityManager is closed. Error in line 59: The EntityManager is closed. Error in line 60: The EntityManager is closed. Error in line 61: The EntityManager is closed. Error in line 62: The EntityManager is closed. Error in line 63: The EntityManager is closed. Error in line 64: The EntityManager is closed. Error in line 65: The EntityManager is closed. Error in line 66: The EntityManager is closed. Error in line 67: The EntityManager is closed. Error in line 68: The EntityManager is closed. Error in line 69: The EntityManager is closed. Error in line 70: The EntityManager is closed. Error in line 71: The EntityManager is closed. Error in line 72: The EntityManager is closed. Error in line 73: The EntityManager is closed. Error in line 74: The EntityManager is closed. Error in line 75: The EntityManager is closed. Error in line 76: The EntityManager is closed. Error in line 77: The EntityManager is closed.

**Comment by shredding** [comment]
Yeah, of course you can't map country id twice. You have yo remove the
country id property, i guess.

---

... via Phone.

**Comment by iparker** [comment]
Another error appears when importing billing_country:

Errors: Error in line 1: Found entity of type on association Shopware\Models\Customer\Billing#country, but expecting Shopware\Models\Country\Country Error in line 2: Found entity of type on association Shopware\Models\Customer\Billing#country, but expecting Shopware\Models\Country\Country

So it should be possible to import billing_countryID and shipping_countryID in one import?!? Since the change of the Billing-Model this is not possible.

**Comment by beberlei** [comment]
Its possible to do this (almost) backwards compatible, by changing the "countryId" to be a `@ManyToOne` instead of a `@Column` and then have:

```
public function getCountryId()
{
    return $this->countryId->getId();
}
```

You could then introduce `setCountry()` and `getCountry()`. Problem would be breaking the `setCountryId()`.

**Comment by shredding** [comment]
@iparker : If you're on it, you should fix this in Shipping as well, as it's the same error.

**Comment by dnoegel** [comment]
Hi,

as discussed above: Currently we are not able to merge this pull request. Perhaps you want to update your request as soon as you've found a solution for this (perhaps as beberlei suggested). 

The related Jira-Ticket is still open and can be found here: http://jira.shopware.de/Widgets/Jira/?ticket=sw-6344

**Pull request closed without merging**
