### PR TITLE
Strip content of style and script tags in for long description

### PR DESCRIPTION
**Pull request by sebastianlenz**
Replace <script> and <style> Tags with content. This is important for nice shortdescriptions in listing controller.

Code: $text = preg_replace('@<(script|style)[^>]_?>._?</\1>@si', '', $text);

### CODE REVIEW

**Comment by janbuecker** [comment]
Please provide some information why do you want this PR to be merged.

**Comment by sebastianlenz** [comment]
Hey,
this PR contains optimizion of the sOptimizeText function in "engine/Shopware/Core/sArticles.php". It is useful, if someone has < script > or < style > tags in description_long, that this code is not displayed on listing. Without the modified function <style>and <script> tags will be removed, but the content remains.

**Comment by sebastianlenz** [comment]
i updated you test. please read the comment here: https://github.com/shopware/shopware/commit/e951dd347747771054b78135e751983d0adfab55

**Comment by bcremer** [comment]
@sebastianlenz the test is correct for the current behavior. Of course it has to be adjusted for your PR.
Your PR is momentarily in our internal QA.

The following test cases have been added to reflect the new change:

```
            ['<style>body: 1px solid red;</style>', ''],
            ['<script>alert("foo");</script>', ''],
            ['foo<script>alert("foo");</script>bar', 'foobar'],
            ['foo<style>body: 1px solid red;</style>bar', 'foobar'],
```

**Pull request closed without merging**
