### PR TITLE
[Fix] ID in einer foreach-Schleife durch Class ersetzt.

### PR DESCRIPTION
**Pull request by boriskaiser**
IDs gehören nicht in eine foreach-Schleife. Aus diesem Grund wurden sie in allen Standard-Templates (sitemap/index.tpl) durch Klassen ersetzt. (+ Trim trailing whitespace)

### CODE REVIEW

**Comment by darookee** [comment]
+1

**Comment by klarstil** [comment]
Hey @boriskaiser,

Thank you for the Pull Request. Unfortunately we couldn't merge it in our master origin right now due to the fact that we're in the middle of the development to get the 4.0.5 up and running. We'll supposedly merge it right after the release of 4.0.5, so your Pull Request will be released with 4.0.6.

Thank you for your understanding.

Best regards,
klarstil

**Comment by boriskaiser** [comment]
Hey @klarstil,

I'm fine with it.

**Comment by dnoegel** [comment]
Hi @boriskaiser,

I'm sorry to inform you, that - after evaluating it again - we are currently not able to merge your pull request. You are absolutly right that those IDs should be replaced. However we need to keep some backward compability in order not to break existing plugins/extensions. Even if the current behaviour is wrong, we can not break solutions making use of it.

We really appreciate your effort and hope for further contributions,

Best regards,

Daniel

**Pull request closed without merging**
