### PR TITLE
fix cookie removal for www domains

### PR DESCRIPTION
**Pull request by mkreusch**
## 1. Why is this change necessary?
Cookies that are set on .domain.tld currently do not get removed by the cookie removal service, if the shop runs on www.domain.tld
Since major cookies by tracking services (e.g. Google Analytics, Hotjar, ...) use cookies on .domain.tld the user's cookie preferences are bypassed. **This is currently causing serious privacy issues!**

### 2. What does this change do, exactly?
It adds a www-stripped domain to the overwriting cookie, thereby making sure that both www and non-www domains are addressed. (https://stackoverflow.com/questions/1062963/how-do-browser-cookie-domains-work)

### 3. Describe each step to reproduce the issue or behaviour.

1. The shop has to run on a www domain and the Shopware cookie settings shall be set to either not allow any cookies before giving consent or only allow technically required cookies
2. Manually set a cookie on .yourdomain.tld
3. Open any shop page without accepting cookies
4. Notice that the cookie does not get removed

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
This needs to be done in both domains. With www and without. Otherwise the Shopware Cookies itself are not removed anymore :thinking:

**Comment by mkreusch** [comment]
@shyim 
Thanks for your comment!
Obviously you are right with that. I screwed it up in my test so it seemed to work for both hosts. I added the generic host=null to it to not interfere with the original functionality but only add the new stripped host.

**Comment by shyim** [comment]
The CI is failing

**Comment by mkreusch** [comment]
Do have any idea why?

**Comment by shyim** [comment]
https://github.com/shopware/shopware/pull/2379/checks?check_run_id=1160554921#step:6:22 fix your code style

**Comment by mkreusch** [comment]
Sorry - there was a space missing - after all that was probably more effort than fixing it by yourself. Sorry for that!

**Pull request closed without merging**
