### PR TITLE
[next] Use new tag service argument type

### PR DESCRIPTION
**Pull request by jeboehm**
Symfony 3.4 allows you to collect tagged services without creating a compiler pass.
http://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services

Sorry, I had to update some more dependencies... 😫

### CODE REVIEW

**Comment by janbuecker** [comment]
@jeboehm yay, I don't have to do this anymore 👍  but there are more locations of tagged services. Please catch'em all!

**Comment by Haehnchen** [comment]
:+1:

**Comment by janbuecker** [comment]
Merged with 0664d876290a7dad85261f9466950208efb69c74. Thanks 👍

**Comment by jeboehm** [comment]
yeeaaaah

**Pull request closed without merging**
