### PR TITLE
Fix recalculation of invoice amount for taxfree orders

### PR DESCRIPTION
**Pull request by andrewisplinghoff**
This fixes a bug concerning tax-free orders, to reproduce proceed as follow:
- Generate a tax-free order. The invoice amount will be equal to the net invoice amount, which makes sense since no taxes apply.
- Make changes to the order positions, e.g. add a new order position and save it
- **Expected behaviour:** the order amount still is a net amount without taxes
- **Actual behaviour:** the order amount is now a gross amount including taxes, which does not make sense, since this is a tax-free order

This PR also makes the code easier to understand, since previously the variable `$invoiceAmountNet` was used to sum up gross amounts in case of a net order, which is quite confusing.

### CODE REVIEW

**Comment by hlohaus** [comment]
Hey,
internally there is already a pull request for the ticket SW-14351.

`if ($this->taxFree) {`
`$this->invoiceAmountNet = $invoiceAmount + $this->invoiceShippingNet;`
`$this->invoiceAmount = $this->invoiceAmountNet;`
`} elseif ($this->net) {`
`$this->invoiceAmountNet = $invoiceAmount + $this->invoiceShippingNet;`
`$this->invoiceAmount = $invoiceAmountNet + $this->invoiceShipping;`
`}`...

**Comment by andrewisplinghoff** [comment]
As far as I can see, both modifications are equivalent with regards to functionality. I would still propose to merge this PR as it fixes the confusing variable naming.

**Comment by samuelvogel** [comment]
This PR is obsolete now since https://github.com/shopware/shopware/commit/bdc1c83a3b52ada60503dacdfdaced39e8d393e3 was merged.

**Comment by bcremer** [comment]
Thank you @samuelvogel, closed this PR now.

**Pull request closed without merging**
