### PR TITLE
NTR - remove unnecessary deprecations

### PR DESCRIPTION
**Pull request by teiling88**
### 1. Why is this change necessary?
Cause this repo will be shopware 6.0 :-D

### 2. What does this change do, exactly?
removes unneeded deprecation and warnings/erros

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
what about changing 6.0 to 5.8 and removing them then?

**Comment by teiling88** [comment]
not my business @mitelg :-D

**Comment by teiling88** [comment]
ok @mitelg I changed it to 5.8 so @shyim can create the removal pr :trollface:

**Comment by shyim** [comment]
Thanks

**Pull request closed without merging**
