### PR TITLE
Added event to modify query in ListProductGateway

### PR DESCRIPTION
**Pull request by oktupol**
### 1. Why is this change necessary?

With this change, it's now possible to modify the query used to display products in the store front.

### 2. What does this change do, exactly?

It adds an event to which plugin developers may subscribe

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by oktupol** [comment]
While this works, I haven't found any way to decorate `ListProductGateway` without breaking other decorators. The only way I found to modify the query in a decorator was following:

```php
<?php
class ListProductGatewayDecorator extends ListProductGateway
{
    public function __construct($connection, $fieldHelper, $hydrator, $config) {
        parent::__construct($connection, $fieldHelper, $hydrator, $config);
    }

    protected function getQuery($numbers, $context) {
        $query = parent::getQuery($numbers, $context);

        // apply magic

        return $query;
    }
}
```

If I have another decorator `OtherDecorator`, which comes first in the decoration chain, `OtherDecorator`'s changes would be discarded, or, to be more precise, `OtherDecorator` would never be loaded.

**Comment by oktupol** [comment]
Would it be ok to have a `ListProductQueryService` into which I source the getQuery-method out?

**Comment by soebbing** [comment]
What you are doing in the code above is not a decoration, that's why other decorators are breaking.

But I can see what you're trying to achieve, I am not entirely sure what the best way to implement this would be.

My first thought would be something like the `FieldHelper`-class in the the `ListProductGateway`: a simple Helper-class with an interface that plugins can decorate, which would allow for a modification of the `QueryBuilder`.

What do you think about that?

**Comment by oktupol** [comment]
That sounds good. I'll try that

**Pull request closed without merging**
