### PR TITLE
removed unnecessary assignment - micro fix

### PR DESCRIPTION
**Pull request by alpham8**
### 1. Why is this change necessary?
It removes unnecessary memory usage (never really used variable).

### 2. What does this change do, exactly?
It frees memory.

### 3. Describe each step to reproduce the issue or behaviour.
not applicable

### 4. Please link to the relevant issues (if any).
not applicable

### 5. Which documentation changes (if any) need to be made because of this PR?
not needed

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ x ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
That's not unnecessary. loadTemplate resets all view vars

**Comment by mitelg** [comment]
maybe then we could move into the `if` ?

**Comment by alpham8** [comment]
> That's not unnecessary. loadTemplate resets all view vars

So, it reassign the vars to the new template after the if block, right?

**Comment by shyim** [comment]
Can you just move the calls to the if a condition like telgi said @alpham8

**Comment by alpham8** [comment]
@shyim @mitelg done ;-)

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
