### PR TITLE
SSL fix for w3.org, schema.org and facebook.com

### PR DESCRIPTION
**Pull request by christopherholst**
If a resource is available over SSL, then always use the https:// URI.

### 1. Why is this change necessary?
Loads page resources using protocol relative URIs
Loading a resource using protocol relative URIs allow it to be requested over HTTP and opens the door for Man-on-the-side attacks. If a resource is available over SSL, then always use the https:// URI.

### 2. What does this change do, exactly?
change from http to https urls where https urls are available

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by christopherholst** [comment]
@soebbing please, here are all fixes with a check whether this url exists as https.

**Comment by tinect** [comment]
Is it on purpose and verified you edited namespaces (w3.org), too? This won't be requested, as it's just a "text" (namespace). I cannot get any information these can be valid.

Edit: Changing namespace in svg will break them - at least in preview in chrome and github.

**Review by tinect — CHANGES_REQUESTED** [review]
Please revert all w3.org-changes, these are invalid...
https://stackoverflow.com/questions/30707609/xml-namespace-uri-with-https/30761004#30761004
https://github.com/validator/validator/issues/692
https://stackoverflow.com/questions/22976359/xml-namespace-a-security-issue

**Review by tinect — COMMENTED** [review]
This makes it more broken, as you added non-namespace `https://www.w3.org/TR/SVG2/`

**Pull request closed without merging**
