### PR TITLE
SW-25604 - Added support to display unit and unit name in article list component

### PR DESCRIPTION
**Pull request by fibenacci**
### 1. Why is this change necessary?

customers want to see units in the product list

### 2. What does this change do, exactly?

display unit and unit name of each product

### 3. Describe each step to reproduce the issue or behaviour.

if you want to select the units in the article list there are any.

### 4. Please link to the relevant issues (if any).

https://issues.shopware.com/issues/SW-25604

### 5. Which documentation changes (if any) need to be made because of this PR?

none 

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by h3llj0ck3y** [comment]
Why does the check failed?

**Comment by fibenacci** [comment]
Did I forgot something or why its still marked as "Incomplete"?

**Comment by mitelg** [comment]
@h3llj0ck3y it isn't marked as incomplete? :thinking:

**Comment by fibenacci** [comment]
Hehe. Sorry my fault. Great, thanks for the Quick-Pick. :D

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
