### PR TITLE
fix: backend order detail position, missing Article Detail id on add …

### PR DESCRIPTION
**Pull request by Dominikrt**
…or update position

### 1. Why is this change necessary?
Shopware Backend Order Position Module don't save `articleDetailID` from later added/updated article. 

This cause issues with Doctrine, trying to get the articleDetail from orderPosition.

```
+---+-------+---------+------------------+---------------+
|id |orderID|articleID|articleordernumber|articleDetailID|
+---+-------+---------+------------------+---------------+
|208|59     |78       |SW10079           |141            |
|209|59     |0        |SHIPPINGDISCOUNT  |null           |
|210|59     |215      |SW10213.3         |null           |
|212|59     |113      |SW10114           |null           |
+---+-------+---------+------------------+---------------+
```
Here a query result with the bug from the `s_order_details` table with 'SW10213.3' and 'SW10114' as later added position.

```
+---+-------+---------+------------------+---------------+
|id |orderID|articleID|articleordernumber|articleDetailID|
+---+-------+---------+------------------+---------------+
|208|59     |78       |SW10079           |141            |
|209|59     |0        |SHIPPINGDISCOUNT  |null           |
|210|59     |215      |SW10213.3         |759            |
|212|59     |113      |SW10114           |178            |
+---+-------+---------+------------------+---------------+
```

Here the same query with the fix

### 2. What does this change do, exactly?
Later added/updated Positions get saved with `articleDetailID`

### 3. Describe each step to reproduce the issue or behaviour.
Open a order in Backend and add a position 

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @Dominikrt 

thanks for your contribution :+1: 

Would you mind extending the following test, to ensure the correct behaviour? [OrderTest](https://github.com/shopware5/shopware/blob/5.7/tests/Functional/Controllers/Backend/OrderTest.php)

**Comment by Dominikrt** [comment]
Hi @mitelg,
thanks for the feedback, I add a test to check the relation.

**Comment by mitelg** [comment]
hey @Dominikrt 

your changes looks good! thank you very much for that :+1: 

Unfortunately it seems that we have problems with the pipeline. So we need to check that first :see_no_evil: sorry for the inconvenience here. Once it is up again and green, your change is ready to merge :muscle:

**Comment by mitelg** [comment]
hey @Dominikrt 

after a rebase the CI should work again

**Comment by Dominikrt** [comment]
Hi @mitelg,
thank you, it looks better now with the tests

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @Dominikrt 👍🎉💙

**Pull request merged**
