### PR TITLE
Update Basic.php

### PR DESCRIPTION
**Pull request by jetwes**
fix for php bug https://bugs.php.net/bug.php?id=41820 which is causing bad backgrounds (mixed #ffffff and #fefefe) in thumbnails

### CODE REVIEW

**Comment by bcremer** [comment]
Hi @jetwes, thanks for your contribution.

I was not able to reproduce this issue.
1. Created a pure white #fff 800*600px JPG
2. Uploaded as product image
3. Downloaded generated thumbnails

I tried that with a jpg and png file.

In both cases the generated thumbnails were pure #fff.

**Comment by jetwes** [comment]
Hi @bcremer ,

have a look at the pictures at the shopware Demo Shop. There you can see Problem as well. 
I think a pure white image doesn't have the effect, because imagecopyresampled() has no other colors than white for resampling. If there's a bit of black in the middle you can see this. Or just try this for example (the background is pure white)
lz-16742-strickjacke-fransen-schwarz_1_260x173
lz-16742-strickjacke-fransen-schwarz_1

**Comment by bcremer** [comment]
Link to bugtracker report: http://jira.shopware.de/?ticket=SW-9404

**Comment by bcremer** [comment]
As far as I can see the fix originates from this blog entry dated back in 2011: http://jasuten.com/background-noise-in-magento-image-resize/

**Comment by jetwes** [comment]
correct!

**Comment by jetwes** [comment]
you can see similar problems in all major shop systems - all caused by the php bug i mentioned before - here is an example for oxyd: https://bugs.oxid-esales.com/view.php?id=3642 . The first fix was for magento in 2011

**Comment by bcremer** [comment]
Measured performance of the patch today. 
Unfortunately the patch has a huge perfomance impact. 
The time to regenerate all thumbnails for our demodata doubled.

Without patch:

``` bash
~/www/master (master) 
$ time ./bin/console sw:thumbnail:generate -f
./bin/console sw:thumbnail:generate -f  58.38s user 1.71s system 99% cpu 1:00.28 total
```

With patch:

``` bash
~/www/master (master) 
$ time ./bin/console sw:thumbnail:generate -f
./bin/console sw:thumbnail:generate -f  125.04s user 1.54s system 99% cpu 2:06.80 total
```

Under these circumstances we cannot include this patch in the shopware core.

If you rely on perfect thumbnail generation in a project you can write a plugin that replaces the default thumbnail generator. Please have a look at https://github.com/bcremer/SwagAsyncImageGenerator to get an idea how that would look like.

**Pull request closed without merging**
