### PR TITLE
Added smarty block to Shopware.apps.Config.model.CountryAttribute

### PR DESCRIPTION
**Pull request by FiveDigital**
This block is missing and needed for adding new attributes to the country model.

### CODE REVIEW

**Comment by shyim** [comment]
I had the same problem last week.
The Attributes in Config.Model are useless, because he uses the attributes from Base.Model.
https://github.com/FiveDigital/shopware/blob/feature/countryAttributes/themes/Backend/ExtJs/backend/config/model/form/country.js#L62
:)

**Comment by FiveDigital** [comment]
I found that issue, too. I tried to fix it but wasn't successful. So I think the whole country attribute thing is broken and will hopefully be fixed with the new attributes feature in 5.2 that has been announced quite a few times.

**Comment by janbuecker** [comment]
Hi @FiveDigital and thanks for your PR.

With Shopware 5.2, we've removed the attribute models in the backend due to the new attribute management.

**Comment by FiveDigital** [comment]
We will check the new attribute system when upgrading to 5.2 in our customer's project. If it doesn't fit our needs I will create a new PR for 5.2

**Pull request closed without merging**
