### PR TITLE
!!![HOTFIX] remove broken unit test

### PR DESCRIPTION
**Pull request by htuscher**
The commit 11b2da22bbc4a615a9c22bab9d77e6803046e50c introduced a defect unit test that doesn't make much sense but causes the test suite to fail. Why was this merged in the first place?

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| How to test?     | Run unit tests on current 5.2 branch

### CODE REVIEW

**Comment by bcremer** [comment]
Please calm down.

Using exclamation marks won't make your PR any better.
I am able to reproduce the failing unit test and will have a look into it.

> Why was this merged in the first place?

Because we are Humans and errors happen.

**Comment by bcremer** [comment]
The failing test was moved to the functional testgroup because it has dependencies to the booted application.
Fixed with commit https://github.com/shopware/shopware/commit/e9eaeab68d6573ce8120c6c1bce4201ae66d3cbf.

Thanks for reporting but please keep it calm and constructive in the future - a failing unit test is _not_ the end of the world.

**Comment by htuscher** [comment]
Sorry but the comment was not meant to be interpreted as I'm angry, I was just wondering if you're not running pre-merge unit-tests with travis. As I know it from other open source projects, such a merge would have never happened, because the tests would have failed.

**Comment by bcremer** [comment]
We are using pre-merge builds indeed (Atlassian Bamboo internally and Travis-CI for Github). 
But a miss-configuration in the test-runner prevented that error from being detected.

This has been fixed with commit https://github.com/shopware/shopware/commit/d55bb86999c76e5dd3381009ce8297ca00ce9302.

Before:
https://travis-ci.org/shopware/shopware/jobs/179720071#L939

After:
https://travis-ci.org/shopware/shopware/jobs/179726493#L939

**Pull request closed without merging**
