### PR TITLE
[BUGFIX] make setPaymentStatus/setOrderStatus work again with status mails

### PR DESCRIPTION
**Pull request by philippmahlow**

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks for your PR @philippmahlow :+1: 

I'll just add a few information I tracked down regarding this issue.

Occurences of `\sOrder::createStatusMail`

Broken:
- `\sOrder::setPaymentStatus` (wrong `createStatusMail` parameter)
  - called by: Abstract class `\Shopware_Controllers_Frontend_Payment::savePaymentStatus`
  - not directly used by shopware core but in third party plugins
- `\sOrder::setOrderStatus` (wrong `createStatusMail` parameter)
  - Method is not used inside shopware core but in third party plugins

Working:
- `\Shopware_Controllers_Backend_Order::getMailForOrder` (right `createStatusMail` parameter)
  - called by `\Shopware_Controllers_Backend_Order::saveAction` 
  - Status mails from backend should work like expected

**Comment by philippmahlow** [comment]
Hi guys,
when will this get merged? We had the same issue again after updating one of our client's shop some days ago and some of our plugins won't work as expected, which is annoying, because we want to publish them or have published them already.
Thanks in advance
Philipp

**Comment by bcremer** [comment]
Hi @philippmahlow,

we'll consider this for for Shopware 4.3.3.

Greetings,
Benjamin

**Comment by philippmahlow** [comment]
Hi @bcremer,
thanks, that would be great.
Greetings,
Philipp

**Comment by philippmahlow** [comment]
Hey folks,

this fix is not included in 4.3.3 RC. Why?

Greetings 
Philipp

**Comment by bcremer** [comment]
Hi @philippmahlow, 

we haven't merged all Github tickets for Shopware 4.3.3 RC1 yet.
I'll merge the remaining ones soon.

**Pull request merged**
