### PR TITLE
update Shopware-Font

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
- adding new icons: instagram, xing, youtube + circle-versions
- remove font-type .eot cause it's just for internet explorer which supports woff, too

### 2. What does this change do, exactly?
- used same font as Shopware used for the other ones: Entypo+
- change shopware's instagram-icon to instagram3, cause implementing new one including circle-version
- correct link to styletile in icons.less
- fonts were generated by IcoMoon resulting a smaller size for woff and ttf: 69KB => 51KB
- adds woff2 font-type which is much smaller than gzipped woff

icons

### 5. Which documentation changes (if any) need to be made because of this PR?
styletile

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by tinect** [comment]
#1539 becomes superfluous with this commit

**Comment by mitelg** [comment]
@tinect then close #1539 ? :smile:

**Comment by mitelg** [comment]
~~@tinect adding woff2 is already done in this PR https://github.com/shopware/shopware/pull/1515 please note that the package.json needs an update~~

sorry, that is something else, my fault :blush:

**Comment by tinect** [comment]
sorry, rebase-fail

**Pull request closed without merging**
