### PR TITLE
Add missing smarty block to frontend/detail/image.tpl

### PR DESCRIPTION
**Pull request by screeny05**
This PR adds a new block `frontend_detail_images_image_slider_slide` to the detail image smarty file. This block surrounds the content of the image-slider slide, so the developer is able to add images to the slide after the thumbnail-images.

## Description
Please describe your pull request:
* Why is it necessary? Improve developer experience
* What does it improve? Moar BLOCKZ! 😍 
* Does it have side effects? No

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| How to test?     | Overwrite the block `frontend_detail_images_image_slider_slide` in a template-file inheriting from `frontend/detail/image.tpl`

### CODE REVIEW

**Comment by screeny05** [comment]
Whoah there, what's the matter with this one? Originally i've only added a block, but the commit-history looks a little bloated. Should i create a new PR for this?

**Comment by janbuecker** [comment]
Yes, it may have broken your history as we rebased 5.3 because of a merge failure recently.

Just adding blocks is okay. Changing them results in a BC break and won't be merged any time soon.

**Comment by screeny05** [comment]
So, then this PR won't contain breaking changes and can get merged in 5.3

**Comment by shyim** [comment]
Hey @screeny05 ,
can you please sign the CLA? otherwise we cannot merge the pull request and please squash the commits

**Comment by shyim** [comment]
Hey @screeny05 ,
can you please fix your Branch?

**Pull request closed without merging**
