### PR TITLE
[imported] SW-7626 - Fix scrolling error

### PR DESCRIPTION
**Pull request by aragon999**
When clicking on the comment link, for a better user experience not only the tab should change, but we should also scroll down to the form.

### CODE REVIEW

**Comment by dnoegel** [comment]
Hi,

generally looks good - but you should provide a short description / usecase

Thanks,

Daniel

**Comment by aragon999** [comment]
Hey,

okay I thought adding the ticket number would be enough. I also added a short description now.

Max

**Comment by dnoegel** [comment]
Hey,

thanks, didn't see the ticket reference. We've just imported the PR and will put that into QA:

Best regards,

Daniel

**Comment by bcremer** [comment]
Merged as https://github.com/ShopwareAG/shopware-4/commit/b4c5297cb7e433d79af209cb508bff8aa5192b24

Thank's for your contribution :+1:

**Pull request closed without merging**
