### PR TITLE
Remove PHPUnit 7/8 switch

### PR DESCRIPTION
**Pull request by pascalheidmann**
### 1. Why is this change necessary?
With `@before` and `@after` annotation we are able to avoid the problems with the changed function signature PHPUnit introduced with the switch to PHPUnit 8.

### 2. What does this change do, exactly?
Replace build-in `setUp` and `tearDown` methods in Enlight's `TestCase` classes with equivalent functions with `@before` and `@after` annotation.
This worked out of the box with ~2579 of 2580 testcases but `Shopware\Tests\Functional\Plugins\Core\HttpCache\BootstrapTest::testCacheableRoute` which had some weird plugin reloading bug. By fixing this I also introduced the `DatabaseTransactionBehaviour` trait so there won't be any changes to the database which can cause side effects and require otherwise manual cleanup.

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
As already in Gitter mentioned we can't do that.
This would be a breaking change. That bridge is already removed in 5.7 branch.

**Comment by pascalheidmann** [comment]
@shyim what exactly would be breaking?

**Comment by shyim** [comment]
Ahh nvm. 
Did you test it with both PHPUnit versions?

**Comment by pascalheidmann** [comment]
@shyim both phpunit 7.5 (?, prebundled) and 8.5 run through but there had been some warnings with version 8 of deprecated assertions. But that is another story I guess (or are they already fixed in 5.7?)

**Comment by shyim** [comment]
Deprecations already gone at 5.7 branch.

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
