### PR TITLE
Added new option to AdvancedMenu

### PR DESCRIPTION
**Pull request by Isengo1989**
### 1. Why is this change necessary?
See also -> https://github.com/shopware/shopware/pull/1962

Imagine a shop with a lot of customergroups and a big menu (that is always the same). Every time a user logs in, a new menu will be generated and this will take a long time if you have +150 categories. There should be a way to exclude customergroups to be in the cache key.

auswahl_009

auswahl_242

Espacially the checkout (login/register) is critical, because users will more likely dicard their shopping cart if the login takes longer then a few seconds.

### 2. What does this change do, exactly?
This change adds a new form field **excludeCustomergroup** which will decide if the customergroup will be used in the cache key or not.

The option (boolean) is set to 0 by default (same behavior as before) and even with the plugin not reinstalled it is not true and therefore the customergroups will be considered as usual. I also added the shop scope for caching, cachetime and hoverDelay.

### 3. Describe each step to reproduce the issue or behaviour.
Browse in a big shop (+150 categories) and login with customergroup which is not default.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Isengo1989** [comment]
@PaddyS created a new PR to have a clean start and weekend laziness :smile:

**Comment by shyim** [comment]
The migration is still wrong. See https://github.com/shopware/shopware/blob/5.5/_sql/migrations/406-add-advanced-menu-listeners.php#L13 as example

**Comment by Isengo1989** [comment]
@shyim so the check if the plugin is active or not should not be in the query? Just saw I copy and pasted the wrong class name anyways - so i will fix that too.

**Comment by shyim** [comment]
Remove active from condition AND execute the query like in the example to check that the plugin is installed.

**Comment by shyim** [comment]
Thanks for the Contribution! :blue_heart:

**Pull request closed without merging**
