### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by neomobil**
This is a hungarian translation

## Description
Please describe your pull request:
* Why is it necessary?
* What does it improve?
* Does it have side effects?

Hello!
This is just a begin of a Hungarian translation. No side effects.

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | no
| Related tickets? | no
| How to test?     | no

### CODE REVIEW

**Comment by mitelg** [comment]
hey @neomobil 

thanks your contribution :+1: 
we appreciate your work, but we don't add new language like that in Shopware :wink: 

Shopware comes with English and German per default. If you want to add new languages, you can join our crowdin project -> https://crowdin.com/project/shopware 
if a translations has reached a specific amount there, we will release it as a new plugin in our store like these ones: http://store.shopware.com/en/extensions/language-internationalisation/?p=1&o=2&n=21&c=2019&s=25

So please join us on crowdin, we are looking forward to it :blush: :+1: 

Best regards

**Comment by neomobil** [comment]
Hello!
Will it be a free package when i translate it in crowdin?

Takó Kornél

www.neomobil.hu

**Comment by mitelg** [comment]
Yes, of course! Just like the other ones

**Comment by neomobil** [comment]
Thanks

Takó Kornél

**Pull request closed without merging**
