### PR TITLE
Changed button label for "Perform order" button

### PR DESCRIPTION
**Pull request by jkrzefski**
Now it says, what it actually does.

### 1. Why is this change necessary?
The button label is confusing and does not make clear what it does.

### 2. What does this change do, exactly?
Change the label to more specifically state the buttons functionality.

### 3. Describe each step to reproduce the issue or behaviour.
Read the button text.

### 4. Please link to the relevant issues (if any).
None.

### 5. Which documentation changes (if any) need to be made because of this PR?
None.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by jkrzefski** [comment]
I was just wondering: What exactly does this `Quick-Pick` label mean?

**Comment by PaddyS** [comment]
Hey @jkrzefski,

you can find all the labels and their meaning here: [contribution guideline](https://developers.shopware.com/community/contribution-guideline/#the-developing-workflow-on-github)

**Comment by larsbo** [comment]
Quick Pick
> You are a lucky one! The changes you provide are only a small fix which is easy to test and implement. Our developers decided to quickly integrate this to our software. 


Quickly
😏

**Comment by PaddyS** [comment]
Pic

**Pull request closed without merging**
