### PR TITLE
Update FontFaceKit and using woff2 + src:local fix

### PR DESCRIPTION
**Pull request by Hotte512**
### 1. Why is this change necessary?

Speeds up a bit... woff2 is smaler and used by modern Browsers like edge:) as of 04/06/2016
And fixing local source for the font.

### 2. What does this change do, exactly?

-Updating the FontFaceKit from https://github.com/FontFaceKit/open-sans as of 2018-01-10

-Adding .woff2 files in font.less

-Fixing src:local in font.less as seen on https://fonts.googleapis.com/css?family=Open+Sans:400,600,700 / https://developer.mozilla.org/de/docs/Web/CSS/@font-face
May fix this ISSUES: https://issues.shopware.com/issues/SW-20451 / https://issues.shopware.com/issues/SW-20548

-Adding .woff2 to the Expire Files in the .htaccess (Responsive/Gruntfile)
-Adding .woff2 to the Expire Files in the .htaccess (sw root)

### 3. Describe each step to reproduce the issue or behaviour.

Slow... as webpagetest, dareboost or gtmetrix shows up fonts are big and slow.
https://issues.shopware.com/issues/SW-20548
https://issues.shopware.com/issues/SW-20451

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by Hotte512** [comment]
@klarstil another tryout... (https://github.com/shopware/shopware/pull/1462) hopefully I did everything right this time? (just learnd about branches...;)
Btw. I can not sign CLA - getting 404 on https://developers.shopware.com/community/contribution-guideline/CLA

this could also go into some 5.3.x if 5.4 takes some more time...

And may be u can tell me how to get an woff2 for shopware.woff  :) (icon-set.less) as seen on https://github.com/shopware/shopware/pull/863 / https://issues.shopware.com/issues/SW-17240

**Comment by Hotte512** [comment]
hmm.. anything wrong / to do?

**Comment by Hotte512** [comment]
Off topic question... If I like to get CloudFlare  rocketloader running I would need to disable it for certain js, especially csfr, by adding 
 
<script data-cfasync="false" ....></script>

Would this be an possible commit?

**Comment by soebbing** [comment]
Thank you for your support, @Hotte512! 🎉 💙

**Pull request closed without merging**
