### PR TITLE
Drop Deprecated Baseprice

### PR DESCRIPTION
**Pull request by hlohaus**
### 1. Why is this change necessary?

See: 
https://developers.shopware.com/developers-guide/shopware-5-upgrade-guide-for-developers/#deprecations-0

Deprecated since 5.2...

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by jkrzefski** [comment]
Travis says, you have to alter the demo data. 😄

**Comment by shyim** [comment]
We need here two migrations caused by blue-green compability 

**5.6 Branch**
Remove select from code
Drop column only on new installation

**5.7 Branch**
Drop column if exists

**Comment by PaddyS** [comment]
Hey @hlohaus,

please rebase this one to Shopware 5.8.

Edit: Nvm, we will do that later. There's no 5.8 as of now.

**Comment by shyim** [comment]
Hey @hlohaus ,
Thanks for your Contribution! :blue_heart:
We have removed the usage in 5.6 and will drop the column with 5.8

**Pull request closed without merging**
