### PR TITLE
fix: restore support for configurator options attributes

### PR DESCRIPTION
**Pull request by mkreusch**
https://issues.shopware.com/issues/SW-27025

Functionality had been broken in this commit:
https://github.com/shopware5/shopware/commit/803467f404046e49d7612f6bdd37c471678b1371#diff-261bf99858c8854bb79143e46685a8e01cf8b121edbec425a592cc0e5cb96d57L4378

### CODE REVIEW

**Comment by PascalThesing** [comment]
@mkreusch, thank you for your contribution.
Could you please run the php-cs-fixer, and try to write a small test reproducing your problem? Then we will merge it :) 
You can execute the php-cs-fixer with ```make fix-code-style```.

**Review by mitelg — CHANGES_REQUESTED** [review]
please target the PR to the "next" branch, as we are currently preparing the 5.7.18 release

**Comment by mitelg** [comment]
hey @mkreusch 

are you still on that? in the meantime we merged back the "next" branch to "5.7", so you just need to rebase your branch here.

**Comment by mitelg** [comment]
hey @mkreusch any progress here?

**Comment by mitelg** [comment]
Hey @mkreusch 

This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request. 

For more information about our contribution guidelines, see https://github.com/shopware5/shopware/wiki/Contribute

**Pull request closed without merging**
