### PR TITLE
fixing inconsistent ordernumber schema

### PR DESCRIPTION
**Pull request by teiling88**
Based on this pull request: https://github.com/shopware/shopware/pull/293

I hope i found every possible article ordernumber in the db schema :-)

### CODE REVIEW

**Comment by dnoegel** [comment]
Thanks @teiling88, looks good for me. Question is, if we shouldn't make it VARCHAR(255) anyway @bcremer? I guess there is no technical reason for the limitation - except the fact, that its a bad index - but that also applies for VARCHAR(40).  What do you think?

**Comment by bcremer** [comment]
I also opt for `VARCHAR(255)`.

But if we are going to change the field we should do some performance research first. Because we are using this fields often times as an index there might be a benefit in changing the type into `CHAR`. See:   http://dba.stackexchange.com/a/1915.

**Comment by ahoehne** [comment]
@bremer habt ihr schon char/varchar Tests gefahren? Wäre da echt an einem Ergebnis interessiert, gerade in Bezug auf InnoDB...
Caching dürfte nach der Logik ja eher suboptimal sein (mehr Speicheverbrauch = weniger Platz zum cachen), dass hat interessanterweise noch keiner in dem Thread angesprochen.

**Comment by teiling88** [comment]
thanks @bcremer

**Comment by bcremer** [comment]
This was fixed with commit https://github.com/shopware/shopware/commit/ac3ddaa6208.

Thanks @teiling88

**Comment by teiling88** [comment]
\o/
Thanks!

**Pull request closed without merging**
