### PR TITLE
email event

### PR DESCRIPTION
**Pull request by ghost**
adding an event before mail is send. so users can add additional receivers or can manipulate mail instance

### CODE REVIEW

**Comment by FiveDigital** [comment]
+1 We need this, too.

**Comment by bcremer** [comment]
Thanks for the pull request.

Have you aware of the  `Enlight_Components_Mail_Send`?

**Comment by ghost** [comment]
Yes i know this event, but some information from forms can be only accessed without freaky tricks in the forms controller.

Von: Benjamin Cremer [mailto:notifications@github.com]
Gesendet: Freitag, 13. Februar 2015 17:05
An: shopware/shopware
Cc: Tim Kellner
Betreff: Re: [shopware] email event (#238)

Thanks for the pull request.

Have you aware of the Enlight_Components_Mail_Send?

**Comment by bcremer** [comment]
Thank you @bestit-tkellner.

You PR was merge in commit: https://github.com/shopware/shopware/commit/1abef58d48f384893402ff4363529de9fbceea57

**Pull request closed without merging**
