### PR TITLE
Change type hinting in Resource Component to interface

### PR DESCRIPTION
**Pull request by FiveDigital**
Changed type hinting from concrete class `Doctrine\Common\Collections\ArrayCollection` to the interface `Doctrine\Common\Collections\Collection` because of problems when using API locally.

I ran into the following error when using the API locally to update prices:

`Catchable fatal error: Argument 1 passed to Shopware\Components\Api\Resource\Resource::checkDataReplacement() must be an instance of Doctrine\Common\Collections\ArrayCollection, instance of Doctrine\ORM\PersistentCollection given, called in /var/www/htdocs/engine/Shopware/Components/Api/Resource/Variant.php on line 592 and defined in /var/www/htdocs/engine/Shopware/Components/Api/Resource/Resource.php on line 276`

An update without prices was no problem at all. After some googleing I found out that this is a common doctrine error and the solution always was to change type hinting to the interface. After changing the type hinting the product got updated with correct prices.

The code causing this error is the following (`$data` come from a CSV file provided by our customer):

``` php
        $number       = $data['ReferenzNr'];
        $price        = doubleval($data['VK']);
        $specialPrice = doubleval($data['VKShop']);

        $params = array(
            'name'        => $data['Beschreibung'],
            'description' => $data['Bemerkungen'],
            'active'      => true,
            'supplier'    => $data['Hersteller'],
            'mainDetail'  => array(
                'prices'  => array(
                    array(
                        'customerGroupKey' => 'EK',
                        'price'            => $specialPrice > 0 ? $specialPrice : $price,
                        'pseudoPrice'      => $specialPrice > 0 ? $price : '',
                        'from'             => 1,
                    )
                )
            )
        );

        try {
            $article = $this->articleResource->updateByNumber($number, $params);
        } catch(\Exception $e) {
            $this->output(sprintf("<error>Cannot update article %s: %s</error>", $number, $e->getMessage()));
        }
```

### CODE REVIEW

**Comment by bcremer** [comment]
Thank's for your feedback. 

Usually these kinds of error are caught by the error handler (\Shopware_Plugins_Core_ErrorHandler_Bootstrap) and just ignored.

Are you running this code outside of the usual shopware scope?

However, we fixed the typehints errors and a few notices with the following commit on master: https://github.com/ShopwareAG/shopware-4/commit/eb6598a3e8da06d17df6f8a7b85dc7c03baa1bda

This fix will be included in Shopware 4.3.1 that will be released soon.

Greetings,
Benjamin

**Comment by FiveDigital** [comment]
Okay here are some details. I'm currently developing an ERP integration for one of our customers. The ERP transfers CSV files to the shop server. I've written an Import Component `ERP\Components\Import` to parse the CSV file and then create or update the products with the API (http://wiki.shopware.de/Shopware-4-Lokaler-Zugriff-auf-die-API_detail_992.html). 

There are two use cases for the import:

1.) We need a cronjob that regularly looks for CSV files
2.) We need a way to manually import a specific CSV file

For the second case I've created a new Command `Shopware\Commands\ImportCommand` which instantiates the Import Command, parses the CSV file and then calls `Shopware\Components\Api\Resource\Article::updateByNumber()`. And that's where this error occurs:

```
PHP Catchable fatal error:  Argument 1 passed to Shopware\Components\Api\Resource\Resource::getManyToManySubElement() must be an instance of Doctrine\Common\Collections\ArrayCollection, instance of Doctrine\ORM\PersistentCollection given, called in /var/www/engine/Shopware/Components/Api/Resource/Article.php on line 1143 and defined in /var/www/engine/Shopware/Components/Api/Resource/Resource.php on line 424
PHP Stack trace:
PHP   1. {main}() /var/www/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/bin/console:39
PHP   3. Shopware\Components\Console\Application->doRun() /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php:121
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/engine/Shopware/Components/Console/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/vendor/symfony/console/Symfony/Component/Console/Application.php:892
PHP   7. Shopware\Commands\ImportCommand->execute() /var/www/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
PHP   8. ERP\Components\Import->importFile() /var/www/engine/Shopware/Plugins/Local/Core/ERP/Commands/ImportCommand.php:42
PHP   9. ERP\Components\Import->import() /var/www/engine/Shopware/Plugins/Local/Core/ERP/Components/Import.php:108
PHP  10. ERP\Components\Import->updateArticle() /var/www/engine/Shopware/Plugins/Local/Core/ERP/Components/Import.php:147
PHP  11. Shopware\Components\Api\Resource\Article->updateByNumber() /var/www/engine/Shopware/Plugins/Local/Core/ERP/Components/Import.php:188
PHP  12. Shopware\Components\Api\Resource\Article->update() /var/www/engine/Shopware/Components/Api/Resource/Article.php:561
PHP  13. Shopware\Components\Api\Resource\Article->prepareAssociatedData() /var/www/engine/Shopware/Components/Api/Resource/Article.php:612
PHP  14. Shopware\Components\Api\Resource\Article->prepareCategoryAssociatedData() /var/www/engine/Shopware/Components/Api/Resource/Article.php:708
PHP  15. Shopware\Components\Api\Resource\Resource->getManyToManySubElement() /var/www/engine/Shopware/Components/Api/Resource/Article.php:1143
```

If you're interested in further investigation I can give you my number and we can talk about this topic together.

**Comment by bcremer** [comment]
OK, I see why this happened.
In Shopware Commands the default error handler is not enabled.
But there is a easy to enable the error handler for certain commands:

```
// in you command
$this->registerErrorHandler($output);
```

This will enable the default error handler that is also used during a default shopware dispatch.

But in Shopware 4.3.1 this issue should be fixed anyway.

**Comment by FiveDigital** [comment]
Registering the ErrorHandler suppresses the errors :thumbsup: But what happens with them? I expected them to appear in a log file but it seems that they are just not printed out. Looking into the `registerErrorHandler()` function I found this:

`if ($errno === E_RECOVERABLE_ERROR) {
    return true;
}`

I think it would be a a good idea to log this kind of error at least in a development / debug mode.

**Comment by bcremer** [comment]
That's totally true.

Unfortunately we have a lot of legacy code and third party plugins that trigger a huge load of errors, That would spam the production logfile.

We're currently reworking the ErrorHandler to integrate some usefull filtering and logging for development purposes.

I started a while ago playing around with an own Shopware Errorhandler. You can find the code here: 
https://github.com/bcremer/SW-Plugin-CrmrDevErrorHandler/blob/master/Bootstrap.php

**Pull request closed without merging**
