### PR TITLE
Support for combo store values in plugin config.xml

### PR DESCRIPTION
**Pull request by shyim**
| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? | Nope |
| How to test? | Example config.xml => https://dpaste.de/gnGL |
## Description

Please describe your pull request:
this PR allows the plugin developer to define the store values in the config file. Currently we must set the combo values in the plugin install (getting form model set new store saving....), that is not so pretty and easy like the other fields :)

### CODE REVIEW

**Comment by bcremer** [comment]
Nice work :+1:
Can you please add a testcase to https://github.com/shopware/shopware/blob/5.2/tests/Unit/Components/Plugin/XmlConfigDefinitionReaderTest.php?

**Comment by shyim** [comment]
Its added

**Comment by bcremer** [comment]
Great. Please just rewrite your testcase a bit so it is as simple as possible like so:

``` php
    public function testCanReadStores()
    {
        $form = $this->SUT->read(__DIR__.'/examples/config_store.xml');
        $this->assertInternalType('array', $form);

        $expected = [
            ['1', 'Test 1'],
            ['2', 'Test 2'],
            ['3', 'Test 3'],
        ];
        $this->assertEquals($expected, $form['elements'][0]['store']);
        $this->assertEquals('Shopware.apps.Base.store.Category', $form['elements'][1]['store']);
    }
```

**Comment by shyim** [comment]
Its changed :)

**Comment by tony-stark-eth** [comment]
pls...

**Pull request closed without merging**
