### PR TITLE
Add phone to order shipping address model

### PR DESCRIPTION
**Pull request by FiveDigital**
You can enter a phone number for you shipping address but it won't be persisted since the column is missing in the model/database. 

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | no
| How to test?     | Enter a phone number in your shipping address. After placing the order the phone number is saved in the `s_order_shippingaddress` table.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @FiveDigital 
thanks for rebasing your PR on 5.3 :+1: 
you should change the migration number. and you have conflicts, which should be resolved

**Review by FiveDigital — COMMENTED** [review]
Resolved merge conflicts

**Comment by mitelg** [comment]
ticket number for tracking: https://issues.shopware.com/issues/SW-17303

**Comment by lhwparis** [comment]
Isnt it possible to merge this into 5.2? Does not break anything and is an important fix in my opinion.

**Comment by FiveDigital** [comment]
This PR was actually based on the 5.2 branch, see #891 But since the PR has been ignored for an half year by Shopware I've asked if it's gonna be merged in 5.2. Unfortunately this won't happen even if we need this in one of our Enterprise customer's installation. It's sad that they ignore PRs for such a long time.

**Comment by lhwparis** [comment]
@FiveDigital :( i understand they do not merge every PR but this is an important fix in my opinion. dont understand why it is open since 6 month.

**Review by roman-1983 — APPROVED** [review]

**Comment by lhwparis** [comment]
@mitelg any news on this PR? or any reason why it is not merged already?

**Comment by soebbing** [comment]
Hi @FiveDigital!
Thank you very much for your PR ❤️  and sorry it took so long. 
I just merged it (https://github.com/shopware/shopware/commit/bfe0e302aeb294b382c6ba07a978d8feb0df54b4) and extended the integration a bit. Your changes will be included in the next release of Shopware.
Again, Thank you for your contribution! 👏

**Pull request closed without merging**
