### PR TITLE
Add a method for retrieving QueryBuilder for suppliers

### PR DESCRIPTION
**Pull request by mioduszewski**
For hooking supplier-query we've added a new method called `getSupplierListQueryBuilder` based on other `get*QueryBuilder`-methods in repository.

### CODE REVIEW

**Comment by janbuecker** [comment]
Thanks for your PR. 

I've already implemented this for the upcoming Shopware version 5.1.3. You can review my changes here https://github.com/shopware/shopware/commit/99c1ab1253abbc23bab0de52718b8e368975ae6a.

Does this commit solve your problem?

**Comment by mioduszewski** [comment]
Thanks for your quick response, @janbuecker. Actually the `getSupplierListQueryBuilder`-method is used in the Article-Repository for getting the supplier in backend. Afaik your commit won't change that behaviour?

**Comment by janbuecker** [comment]
Ah, I see your problem here. PR looks good for me. /cc @bcremer

**Comment by janbuecker** [comment]
Merged with commit 36f99a1eb5e2f81468541407060a9f0a34bb3ce3.

Thank you @mioduszewski

**Pull request closed without merging**
