### PR TITLE
[BUGFIX] Slider initialization

### PR DESCRIPTION
**Pull request by schliflo**
Savely initialize all slider elements even with multiple shoppingworlds on one page.

### CODE REVIEW

**Comment by JenSommer** [comment]
Simples-Minimalistic Responsive Template

         /* Client-specific Styles */
         #outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
         body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0;}
         /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
         .ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */
         .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;} /* Force Hotmail to display normal line spacing.*/
         #backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
         img {outline:none; text-decoration:none;border:none; -ms-interpolation-mode: bicubic;}
         a img {border:none;}
         .image_fix {display:block;}
         p {margin: 0px 0px !important;}
         table td {border-collapse: collapse;}
         table { border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; }
         a {color: #0a8cce;text-decoration: none;text-decoration:none!important;}
         /*STYLES*/
         table[class=full] { width: 100%; clear: both; }
         /*IPAD STYLES*/
         @media only screen and (max-width: 640px) {
         a[href^="tel"], a[href^="sms"] {
         text-decoration: none;
         color: #0a8cce; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
         text-decoration: default;
         color: #0a8cce !important;
         pointer-events: auto;
         cursor: default;
         }
         table[class=devicewidth] {width: 440px!important;text-align:center!important;}
         table[class=devicewidthinner] {width: 420px!important;text-align:center!important;}
         img[class=banner] {width: 440px!important;height:220px!important;}
         img[class=colimg2] {width: 440px!important;height:220px!important;}
         
         
         }
         /*IPHONE STYLES*/
         @media only screen and (max-width: 480px) {
         a[href^="tel"], a[href^="sms"] {
         text-decoration: none;
         color: #0a8cce; /* or whatever your want */
         pointer-events: none;
         cursor: default;
         }
         .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
         text-decoration: default;
         color: #0a8cce !important; 
         pointer-events: auto;
         cursor: default;
         }
         table[class=devicewidth] {width: 280px!important;text-align:center!important;}
         table[class=devicewidthinner] {width: 260px!important;text-align:center!important;}
         img[class=banner] {width: 280px!important;height:140px!important;}
         img[class=colimg2] {width: 280px!important;height:140px!important;}
         
        
         }
      




				

								

												
													 
												
											
										


						

		


				

								


											
										


												


																
																	Re|kre|a|ti|on
																
																
																	 ⟨f.; –; unz.⟩ Erholung
																
																
																	[< lat. recreatio »Erholung, Wiederherstellung«; zu recreare »kräftigen, sich erholen«]
																
															
														


															
														


																
																
																
																	Mein Rechner bleibt (überwiegend) offline und bis einschließlich 6. Juli 2015 befinde ich mich in einer kreativen Pause und kann leider nur bedingt auf Ihre Anfrage reagieren. Ihre E-mail wird nicht weitergeleitet. Bitte wenden Sie sich in dringenden Fällen via SMS, iMessage oder WhatsApp-Nachricht via Handy an mich - ich bin dann so schnell es geht gerne für Sie da.
																
																
																	Ab dem 7. Juli 2015 bin ich energiegeladen für Sie wieder zu 100% erreichbar und freue mich auf spannende Herausforderungen.
																
    
													Bis dahin - mit kreativen Grüßen,Jürgen Sommer

**Comment by bcremer** [comment]
@shopware/shopware-webdev can you please review.

**Comment by schliflo** [comment]
@Phil23 i did dig a little deeper and came up with a better solution that should fix the issue completely. The issue was, that .data() in plugin = $el.data('plugin_' + pluginName); returned the data store of the first element of $el - regardless of it having more elements than one.

**Comment by rzierhofer** [comment]
@schliflo THX!

**Comment by bcremer** [comment]
Merged with commit https://github.com/shopware/shopware/commit/293e4016aa3d89183676ce662c7ca63219688fee.

Thank you @schliflo  :+1:

**Pull request closed without merging**
