### PR TITLE
Added Category Join to Blog getListQueryBuilder function

### PR DESCRIPTION
**Pull request by phoerig**
In some cases it is necessary to get category information from blog article

### CODE REVIEW

**Comment by janbuecker** [comment]
Thanks @phoerig 

We decided to close this PR because of time constraints and limited overall benefit to the product. If this change is still important to you, please create a new issue on https://issues.shopware.com so people can up-vote this feature.

**Comment by phoerig** [comment]
is there any way to add only the hook to the emotion widget?

the query extension i need, i can add otherwise

**Comment by bcremer** [comment]
@phoerig All repositories are hookable so you can modify the query builder via the plugin system like this:

```php
<?php
namespace SwagHookExample;

use Doctrine\ORM\QueryBuilder;
use Shopware\Components\Plugin;

class SwagHookExample extends Plugin
{
    public static function getSubscribedEvents()
    {
        return [
            'Shopware\Models\Shop\Repository::getActiveQueryBuilder::after' => 'afterActiveQuery',
        ];
    }
    public function afterListQueryBuilder(\Enlight_Hook_HookArgs $args)
    {
        /** @var QueryBuilder $return */
        $return = $args->getReturn();

        $return->addSelect(['comments', 'category']);
        $return->leftJoin('blog.category', 'category');

        $args->setReturn($return);
    }
}
```

**Comment by phoerig** [comment]
@bcremer I know, but i think it was goot for all Users to have the category data

**Pull request closed without merging**
