### PR TITLE
Attribute columns should be able to get updated.

### PR DESCRIPTION
**Pull request by roman-1983**
Attribute columns should be able to get updated. This PR changes this behavior and allows updates to a column instead of returning void.

### CODE REVIEW

**Comment by roman-1983** [comment]
Any feedback on this PR?

**Comment by roman-1983** [comment]
ping

**Comment by janbuecker** [comment]
Hi @roman-1983, thanks for your PR. 
Looks good to me. I've scheduled your changes.

Cheers!

**Comment by 3stadt** [comment]
Hi @roman-1983,

now with 5.2 released we were finally able to evaluate your PR.

Since the new attribute system is already implementing this functionality (see \Shopware\Bundle\AttributeBundle\Service\CrudService::update) we will not integrate your PR.

The addAttribute will be deprecated in the next release and removed in 5.3.

**Pull request closed without merging**
