### PR TITLE
Added user specific info to sCONFIRMPASSWORDCHANGE mail

### PR DESCRIPTION
**Pull request by shyim**
## Description
Please describe your pull request:
* Why is it necessary?
It is currently not possible to user firstname or other fields in mail template
* What does it improve?
Adds the fields
* Does it have side effects?
Nope

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | 
| How to test?     |

### CODE REVIEW

**Comment by OliverSkroblin** [comment]
Hi @shyim,

thanks for the pull request. 
Could you please change the following things:
- Don't use the user_addresses
- Customer names are stored (address refactoring) in s_user
- Only select a whitelist of s_user fields (not password, encoder, ...)
- If you want to select attributes too, please consider ambiguous column selection. s_user.id and s_user_attributes.id is duplicated. 
- Please store the user_attributes inside a sub array `attribtues`

**Comment by shyim** [comment]
What would you think if I get the customer model convert it as array and remove some fields like password. So we would have anything about the user in mail context

**Comment by janbuecker** [comment]
I'd prefer a whitelist instead of a blacklist.

**Comment by shyim** [comment]
Aye Aye Captain its updated :)

**Comment by mitelg** [comment]
Thanks again @shyim :+1:

**Pull request merged**
