### PR TITLE
Created additional Smarty-block for configs

### PR DESCRIPTION
**Pull request by agreif84**
I needed an easier way to change the configs in this template-file.

### CODE REVIEW

**Comment by screeny05** [comment]
this is rather similiar: #497, but i like your solution more.

**Comment by shyim** [comment]
We should mention it on the UPGRADE.md to inform the template developers about the new block.

**Comment by agreif84** [comment]
Thanks! I upgraded the file as mentioned.
@screeny05 My solution is for the 5.1-branch, yours is for the newer (5.2). That template-file has been refactored since then.

**Comment by screeny05** [comment]
I see, i'll close my pr, as shopware already implemented this change by themselves.

[5.2/themes/Frontend/Bare/widgets/emotion/index.tpl](https://github.com/shopware/shopware/blob/5.2/themes/Frontend/Bare/widgets/emotion/index.tpl#L7)

**Comment by janbuecker** [comment]
Thanks for your PR.
Like @screeny05 already mentioned, this has already been implemented recently and will be available as of Shopware 5.2 BETA 2.

**Pull request closed without merging**
