### PR TITLE
Add ProductIndexerInterface to ESIndexingBundle

### PR DESCRIPTION
**Pull request by egoist-dd**
## Description

Please describe your pull request:
- Why is it necessary?: Allow to Overwrite ProductIndexer
- What does it improve? Allow ProductIndexter Modifications
- Does it have side effects? no

| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? | no |
| How to test? | Start ElasticSearch Indexing / Updating |

### CODE REVIEW

**Comment by egoist-dd** [comment]
can you please merge this?

**Comment by janbuecker** [comment]
It has been scheduled. Please do not ask or "ping" about when it will be merged.

You can track the status of this PR in the ticket above.

**Comment by janbuecker** [comment]
@egoist-dd we've discussed this PR, but we would like to know, why problem you are trying to solve with this change?

**Comment by Phil23** [comment]
This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request. 

For more information about our contribution guidelines, see https://developers.shopware.com/contributing/contribution-guideline/.

**Pull request closed without merging**
