### PR TITLE
Changes to make db-connection more reliable and restartable in case it fails/break

### PR DESCRIPTION
**Pull request by fuckmaz**
Handling the DB-Connection this way makes way more sense and is more adaptive for the API-Resources.

### CODE REVIEW

**Comment by bcremer** [comment]
Can you please elaborate in which cases this is more reliable. Can you please provide some testcases.

**Comment by fuckmaz** [comment]
We experienced that when the DB-Connection breaks after a long time (in our case it was a Importer-Plugin that has runtimes of about 5 hours) it won't reinitialize itself, which results in Errors with every operation. With these two changes we were able to reinitialize the DB-Connection from our Plugin and continue Insert- and Update-Operations to the DB.

So it's more reliable when the DB-Connection is needed for a long timespan.

**Comment by NiklasTeich** [comment]
@postcatz Have you already tried to manually set set_time_limit, default_socket_timeout and mysql.connect_timeout before executing these long-time plugin scripts? Maybe a possible workaround to override the system defaults in your script.

**Comment by fuckmaz** [comment]
Yes we tried all that. It's not a server-side problem as we found. Our limits were already set to 24hours each.

**Comment by janbuecker** [comment]
Thanks @postcatz 

We decided to close this PR because of time constraints and limited overall benefit to the product. If this change is still important to you, please create a new issue on https://issues.shopware.com so people can up-vote this feature.

**Pull request closed without merging**
