### PR TITLE
Updated fpdi, fpdf and mpdf

### PR DESCRIPTION
**Pull request by MaximilianKresse**
### 1. Why is this change necessary?
FPDI 1.6.2 is deprecated and will no longer be updated. It will throw some warnings like: "Function each() is deprecated since PHP 7.2; Use a foreach loop instead."

### 2. What does this change do, exactly?
Update fpdi, fpdf and mpdf

### 3. Describe each step to reproduce the issue or behaviour.
-

### 4. Please link to the relevant issues (if any).
-

### 5. Which documentation changes (if any) need to be made because of this PR?
-

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Hey @MaximilianKresse,

unfortunately merging of Documents seems to be broken now. Can you check that please? It generates blank pages.

image

**Comment by MaximilianKresse** [comment]
🤦‍♂️ I'm sorry...

Can you check again please?

**Comment by shyim** [comment]
Wohoo looks good for me :tada: . Will be merged then shortly

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
