### PR TITLE
refactor: Prepare Enlight\Event for Shopware 5.8 and fix the phpstan issues

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
This is a first attempt to cleanup the Enlight event system, on the one hand fixing the types and on the other hand updating the deprecations. The complete Enlight event system probably should be replaced completely by the Symfony Event system, but not sure how the exact migration path should look like.

### 2. What does this change do, exactly?
I updated the deprecations and added some new ones and furthermore fixed the phpstan issues of the non deprecated classes. What do you think of the deprecations and the other changes? Are there any objections?
Locally I have also prepared a branch, where I applied the deprecations and changes for Shopware 5.8 (for the Event system), which I will try to regularly rebase.

### 3. Describe each step to reproduce the issue or behaviour.
\-

### 4. Please link to the relevant issues (if any).
\-

### 5. Which documentation changes (if any) need to be made because of this PR?
Once everything is in shape I will add the necessary information to the `UPGRADE.md`. 

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @aragon999 

at first glance, this looks quite good :+1: 

if we want to deprecate things, we should also make sure, that those things could be removed without problems and only if we have proper replacements for them. beside that, we can remove what ever works :grin: 

Exchanging the event system with the Symfony component could work within a 5.8 release. the good thing with Enlight is, that we have a layer between the framework and our application. so simply said, we can call the Symfony component in the Enlight code and remove our "custom" event logic and in best case nothing changes for Shopware and the plugins.

**Comment by aragon999** [comment]
hey @mitelg very good :-)

Currently everything which is deprecated for removal, is unused. As far as I can tell, only the `Enlight_Event_Subscriber_Plugin` is still in use here: https://github.com/shopware5/shopware/blob/f56e358f200efaaf0e1f0227c0127c69b8da7195/engine/Library/Enlight/Plugin/Namespace/Config.php#L148-L155

But, this currently is integrated deep in plugin system (and also in the Shopware default plugins). Therefore I decided to make this class "only" internal, such that we can later safely deprecate and remove it and give plugin developers time to adopt. Maybe we should also deprecate some more methods in the plugin system, or as suggested use the Symfony event system for that. But I think this is somewhat of a different task, when cleaning up the `Enlight_Plugin_*` stuff.

**Comment by mitelg** [comment]
hey @aragon999 any progress here?

**Comment by mitelg** [comment]
as this PR is in draft mode, I will leave it open for now.

**Comment by mitelg** [comment]
Hey @aragon999 

This PR was closed due to inactivity. If this change is still important to you, feel free to create a new pull request. 

For more information about our contribution guidelines, see https://github.com/shopware5/shopware/wiki/Contribute

**Pull request closed without merging**
