### PR TITLE
Change CronjobSynchronizer::addCronjob to consider action not being p…

### PR DESCRIPTION
**Pull request by DerRidda**
…refixed in cronjob.xml but being prefixed in the DB after first run when checking for cronjob to update.

### 1. Why is this change necessary?

The method would previously only check for the cornjobs action exactly as written in the cronjob.xml when checking if this cronjob already exists.

That is insufficient because cronjob actions might be changed on first run when they are not prefixed with 'Shopware_CronJob_' to receive said prefix.

This means that plugin updates, that update cronjobs, which are not prefixed by the plugin creator but were already run at least once, were never found and thus incorrectly created anew.

### 2. What does this change do, exactly?

This change checks that when the id of a cronjob isn't found, the action isn't already prefixed and if it isn't, checks again with the prefix added.

### 3. Describe each step to reproduce the issue or behavior.

Create a small plugin in the 5.2 plugin that has unprefixed cronjobs, run them at least once, change cronjob.xml and bump plugin version, run update, observe a new cronjob is created in the debugger. 

### 4. Please link to the relevant issues (if any).

Potentially https://issues.shopware.com/issues/SW-19529 and/or https://issues.shopware.com/issues/PT-8245

### 5. Which documentation changes (if any) need to be made because of this PR?

None, as far as I can tell.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
No tests, as this component was completely uncovered by tests.
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
Yes, though only comments really apply.
- [ ] I have read the contribution requirements and fulfill them.
Mostly yes with the exception of Upgrade.md

### CODE REVIEW

**Comment by Phil23** [comment]
@DerRidda please always fill out the required description template, otherwise the pull request will be closed. Please see our contribution guidelines for more information.

https://developers.shopware.com/contributing/contribution-guideline/

**Comment by DerRidda** [comment]
I update the description with the template filled out.

**Comment by Phil23** [comment]
@DerRidda sorry, the linked template was old.  I already updated the link. You will see the template each time you create a pull request. So don't skip this in the future.

The latest version can be found here:
https://github.com/shopware/shopware/blob/5.3/.github/PULL_REQUEST_TEMPLATE.md

**Comment by DerRidda** [comment]
Updated with the new template, sorry for the inconvenience.

**Comment by DerRidda** [comment]
This has been in limbo for ages now. Is it still relevant?

**Comment by soebbing** [comment]
Hi @DerRidda, your PR has been merged in abc099b3d870b73677e0b23a5af3e601241d1144, thank you for your contribution! 💙 
We're really sorry it took us so long. 🙏

**Pull request closed without merging**
