### PR TITLE
TASK | Update structured markup for brand in detail view

### PR DESCRIPTION
**Pull request by AryaSvitkona**
### 1. Why is this change necessary?
Markup is deprecated due to [Google documentation](https://developers.google.com/search/docs/advanced/structured-data/product#microdata). That causes a warning in Google Structured Data Test Tool.

### 2. What does this change do, exactly?
Update markup according to guidelines for product brand

### 3. Describe each step to reproduce the issue or behaviour.
1. Open Markup Check Tool by [Google](https://search.google.com/test/rich-results)
2. Provide product detail URL of a Shopware instance
3. Run test 

### 4. Please link to the relevant issues (if any).
no relevant issue

### 5. Which documentation changes (if any) need to be made because of this PR?
no relevant issue

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by xf-** [comment]
I added the same thing with is--hidden as class — avoid some issues with custom style.

**Comment by AryaSvitkona** [comment]
> I added the same thing with is--hidden as class — avoid some issues with custom style.

Thanks, that's an idea.
Since this is my first contribution. Can I just add that class and squash merge that second commit or do I have to wait, because the label "scheduled" is already set?

**Comment by mitelg** [comment]
@AryaSvitkona go for it :+1: 
we will wait until you have set the class on the `div` element

**Comment by mitelg** [comment]
thanks for your contribution @AryaSvitkona   :+1: :tada: :blue_heart:

don't be confused, we merged it on the next branch, which will be merged back to the main branch in a few days

**Pull request closed without merging**
