### PR TITLE
[BUGFIX] Renamed show_net variable in userData additional to show_gro…

### PR DESCRIPTION
**Pull request by wolv-dev**
…ss, cause text in backend is 'display gross'

### 1. Why is this change necessary?
Variable show_net is confusing, cause when TRUE it will display the gross prices.

### 2. What does this change do, exactly?
Renaming the variable name and it's usage in smarty template

### CODE REVIEW

**Comment by wolv-dev** [comment]
@shopwareBot Rebased and retargeted done!

**Comment by mitelg** [comment]
@wolv-dev something went wrong there :blush:

**Comment by wolv-dev** [comment]
@mitelg Yeah, but I don't know what went wrong.
I rebased 5.4 into my branch, but all following commits are added, too.

I attached a screenshot:
bildschirmfoto 2017-10-05 um 14 21 34

**Comment by wolv-dev** [comment]
@mitelg now it's correct

**Pull request closed without merging**
