### PR TITLE
[papercut] SW-15835 - allow the use of custom variables in form subject fields

### PR DESCRIPTION
**Pull request by simkli**
see title for details

### CODE REVIEW

**Comment by htkassner** [comment]
Can you please change target branch to 99-papercuts branch and rebase your branch to resolve all conflicts?

**Comment by htkassner** [comment]
Sorry, I just saw your contribution is based on a 5.2 fork. Begin september when we started the 99 papercuts action we opened the branch 99-papercuts. Would be nice if you could fork this branch for your contribution because 5.2 and 99-papercuts branch are very diverged right now. Would be much easier to merge your code then.
Thank you for your contribution!

**Comment by simkli** [comment]
Done! There was no papercut branch when I created this PR ;)

**Comment by htkassner** [comment]
I know! Thank you anyways!

**Comment by htkassner** [comment]
I´ve tested this and it works fine. We just need to wait until the last test is successfull.

**Pull request merged**
