### PR TITLE
show update-version in plugin-manager

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
The word "Update" is too little :-)

### 2. What does this change do, exactly?
show available version instead of text "Update"
image

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by mitelg** [comment]
how about "Update to v2.0.0" as text?

**Comment by tinect** [comment]
> how about "Update to v2.0.0" as text?

Yes, could be a solution. But looks quite ugly cause the label above will be shorter and looks different. I think the label are clear as they are, aren't they? :-)

**Comment by tinect** [comment]
image
You mean like this? I like! :-) Hopefully it's correct,

Tell me, if correct, so I will squash.

**Comment by PaddyS** [comment]
Hey @tinect,

thank you for your contribution! 💙 
As we previously discussed, this minor change comes with a lot of work to be done.
There's several edge cases to be considered, multiple styles to be changed, etc., so the overall benefit doesn't really fit well to the work that needs to be done.

Therefore we're closing this PR.

**Pull request closed without merging**
