### PR TITLE
added travis CI image for branch 'master'

### PR DESCRIPTION
**Pull request by BjoernSchotte**
This adds the travis ci build image for master branch into the README.md

### CODE REVIEW

**Comment by bcremer** [comment]
Hey Björn,

thanks again for your contribution.

I'm not entirely about the hardcoded `master` in the image url.
I there some kind of github markdown variable containing the current branch?

**Comment by BjoernSchotte** [comment]
See http://docs.travis-ci.com/user/status-images/

"Make sure to select the right branch in the dropdown. The default URL, without the branch parameter, will return the status for the latest build, on any branch. Selecting the desired branch makes sure your image only displays the status for the branch whose stability is most relevant.

You can manually change the branch later, when pasting it into your documentation, should the right branch not show up in the branch dropdown."

So the hardcoded branch is as expected to avoid displaying the status for the latest build, "on any branch".

**Comment by bcremer** [comment]
Merged as https://github.com/ShopwareAG/shopware-4/commit/81515fd36017e6ae776b1dbc4d6c82b9ccbfe46c Into the [next](https://github.com/ShopwareAG/shopware-4/tree/next) branch.

This will be merged from next into master and released as 4.3 in the near future.

Thanks :+1:

**Comment by BjoernSchotte** [comment]
Hmm... now the README.md of https://github.com/ShopwareAG/shopware-4/tree/next branch shows the build status of the master branch. Not sure if this is intended.

**Pull request closed without merging**
