### PR TITLE
Fix SW-19032

### PR DESCRIPTION
**Pull request by DerRidda**
This commit fixes the issue outlined in https://issues.shopware.com/issues/SW-19032

I personally encountered the very same issue in Shopware 5.2.27 the exact same way and came to the same conclusion as the ticket creator.

Either way this is a very, very, insanely easy fix that doesn't break tests (coverage says this condition is covered in 49 tests) and it also allows third-party plugin creators to create entities with circular dependencies that can be used via the API without problems.

### CODE REVIEW

**Comment by wildi1** [comment]
We encountered the same issue in 5.2.27 too and we please Shopware to merge this very easy fix.

**Comment by janbuecker** [comment]
@DerRidda I think there went something wrong with your branch. There are changes from another open pull request in here.

**Comment by DerRidda** [comment]
Oops, seems like I messed things up when making that other PR.
I did not realize PRs could be mutated after they were purely by operations I did on my fork.

Since I didn't branch this commit it's probably not going to be cleaned up, so I would recommend reopening the dupe and use that instead.

TIL to always use a new branch for every commit.

**Comment by mitelg** [comment]
I messed something up :smile: 
sorry for that. we will use your first commit and drop the other one

will be merged soon, btw

Ticket https://issues.shopware.com/issues/SW-19032

**Pull request closed without merging**
