### PR TITLE
Fixed exception, when license key is not readable

### PR DESCRIPTION
**Pull request by shyim**
### 1. Why is this change necessary?
There is a empty RuntimeException without a message

### 2. What does this change do, exactly?
Adds a message to exception

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by JoshuaBehrens** [comment]
I absolutely had this scenario! The shop owner thinks at first it is a plugin problem not a license manager problem.

What about making module and host combined unique? So this scenario will be impossible by structure.

**Comment by shyim** [comment]
That could be a better solution, but the license manager plugin needs also a update and that is closed source 😟 . Otherwise customers who are trying inserting a "duplicate license", seeing a sql error and think w000t my shop is broken.

**Comment by JoshuaBehrens** [comment]
Unfortunately this is true.

@shopwareBot , pls fix

**Comment by mitelg** [comment]
hey @shyim @JoshuaBehrens 
I'm currently working on the license manager plugin and I added a check before inserting into the DB, if there is already an entry for the module/host pair. If so, the entry will be updated. I think that change will make this PR obsolete. Additionally the license manager also supports older Shopware versions. 
What do you guys think about that?

**Comment by shyim** [comment]
Sure it would be better in License Manager. I would leave this pr open, because the empty Exception 😄

**Pull request closed without merging**
