### PR TITLE
Remove unnecessary break in switch statement of the link filter plugin

### PR DESCRIPTION
**Pull request by aragon999**
### 1. Why is this change necessary?
I was currently debugging some problem in the link plugin, it took me some (short) time to figure out if there is some difference between `img` and `a` URLs, or not. Spoiler, it's the same :-)

### 2. What does this change do, exactly?
This change removes this confusion, as the `switch` statement is simplified.

### 3. Describe each step to reproduce the issue or behaviour.
\-

### 4. Please link to the relevant issues (if any).
\-

### 5. Which documentation changes (if any) need to be made because of this PR?
\-

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Review by mitelg — COMMENTED** [review]
why still using the switch statement at all? 🤔

**Comment by aragon999** [comment]
Not sure actually, as there are even some cases which will never match, I will look into that more closely, but I would suggest to completely remove that `switch` statement

**Comment by aragon999** [comment]
So I looked into it, does anyone know why the links for `iframe`s are not rewritten?

**Comment by aragon999** [comment]
Hey @shopwareBot 

thanks for the reply, so you mean that the link for the `iframe` should not be rewritten? Why should that link not be rewritten (especially since there is a check that only internal links will be rewritten).

**Comment by aragon999** [comment]
I have updated the pull request, and also restructured the handling for links in a more reasonable way. Do you see any modification of the behavior of the code for real applications? Or is something relevant and should be correctly handled:
``

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
