### PR TITLE
New order filter "supplier"

### PR DESCRIPTION
**Pull request by pascalheidmann**
### 1. Why is this change necessary?
Sometimes filtering orders by article number isn't enough.

### 2. What does this change do, exactly?
This PR is based on an internal ticket from us done by @NilsEvers and adds a new `suppliers` filter to order list.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Please test your changes also with enabled Elasticsearch backend. These filters have to work in both.

**Comment by pascalheidmann** [comment]
@shyim after digging for at least 1 hour around I cannot find a useful way to make this feature available with ES. But this is a result of the flat structure which already makes filtering by details (and therefore by article) not possible with ES which is already part of shopware for years.

I can hide those fields on ES installations if this would make support easier ;)

**Comment by shyim** [comment]
Can you add a test case for your new filter option? I will build the Elasticsearch part then after importing

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
