### PR TITLE
fixing ascii shopware 4 logo

### PR DESCRIPTION
**Pull request by teiling88**

### CODE REVIEW

**Comment by bcremer** [comment]
Thank you @teiling88.
Are you actually using the shell functionality of the shopware console?

It was deprecated in Symfony 2.8 recently:
https://github.com/symfony/symfony/commit/1c17928e58fa1a4503c616c681aa50221d2aaf1d
https://github.com/symfony/symfony/commit/c23444985bedfdd4ba547973221d2484c60daa2c

I am thinking about removing it starting Shopware 5.2.

Also I don't wan't too be to picky here but the figlet tool we used to generate the logo gives me a slightly different logo:

```
$ figlet shopware5
     _                                       ____  
 ___| |__   ___  _ ____      ____ _ _ __ ___| ___| 
/ __| '_ \ / _ \| '_ \ \ /\ / / _` | '__/ _ \___ \ 
\__ \ | | | (_) | |_) \ V  V / (_| | | |  __/___) |
|___/_| |_|\___/| .__/ \_/\_/ \__,_|_|  \___|____/ 
                |_|  
```

Would you mind updating you Pull Request to the above. Thanks in advance.

**Comment by dnoegel** [comment]
I would remove this kind of version information anyway. If it doesn't come from the __VERSION__ static, it will just be another thing to maintain in the future.

**Comment by bcremer** [comment]
Good thought @dnoegel. The banner image of the updater/install already got rid of the version information. See: https://github.com/shopware/shopware/blob/5.1/recovery/common/src/IOHelper.php#L230

```
     _
 ___| |__   ___  _ ____      ____ _ _ __ ___
/ __| '_ \ / _ \| '_ \ \ /\ / / _` | '__/ _ \
\__ \ | | | (_) | |_) \ V  V / (_| | | |  __/
|___/_| |_|\___/| .__/ \_/\_/ \__,_|_|  \___|
                |_|
```

**Comment by teiling88** [comment]
> Are you actually using the shell functionality of the shopware console?

yes - autocomplete is nice :)

i removed the version number like @dnoegel mentioned

**Comment by dnoegel** [comment]
:+1:

**Comment by bcremer** [comment]
Thank you @teiling88

**Pull request merged**
