### PR TITLE
Allow deleting prices from non default pricegroups

### PR DESCRIPTION
**Pull request by pascalheidmann-bedarf**
### 1. Why is this change necessary?
As soon as you enter a price for a price group that isn't the first (default pricegroup) you can delete one entry but you never are able to use the fallback again (via backend extjs GUI)

### 2. What does this change do, exactly?
Allow deleting the last (first) price row if the pricegroup isn't the default price group (`EK`).

### 3. Describe each step to reproduce the issue or behaviour.
Prerequisite: have at least 2 customer groups
1. create or update existing product by adding a price for the second price group
2. The second price group should show a minus icon for deleting each price row
3. Modify a price in the second customer group and change it back
4. Modify the price in the primary customer group - the change won't be reflected in the second customergroup (won't fix)
5. Delete every row you can for that second customer group -> you can't delete the last row -> you are stuck with the prices

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
I have discussed your Change with our internal QA and Design team.
We want that the last entry of non default group has a new icon in the actioncolumn with class sprite-chain where the user can reset it to fallback to EK. Before setting the fallback, it should show a modal with a warning.

Your current changes works only for scale prices. It should also work for normal prices.

**Comment by pascalheidmann-bedarf** [comment]
@shyim good points! I looked into it again and implemented a confirmation request in a completely new event - this made the hassles I hadn't found a solution for way easier to tackle.
As a bonus I added the missing translation for the `delete` tooltip ;)

**Comment by pascalheidmann-bedarf** [comment]
@shopwareBot pls use my private account @pascalheidmann for credits

**Comment by shyim** [comment]
Hey @pascalheidmann @pascalheidmann-bedarf,

I found two issues with your PR:

* When you have 2 rows and delete one the icon is not shown until you switch the tabs. Maybe a rerender is missing here.
* When you delete / link the row to the default group go to first tab and then back. You can do it again

**Pull request closed without merging**
