### PR TITLE
Fixes wrong Display/Preselection of Shop in Customer Detail View (Backend)

### PR DESCRIPTION
**Pull request by aherking**
### 1. Why is this change necessary?

When creating/updating customers with REST-API you are only able to set shopID, so the "language" will stay default. In customer list the correct Shop is shown, but when opening the detail of a customer there will be the languageId preselected.
customer1
customer3
customer2

### 2. What does this change do, exactly?
Show Shop instead of language

### 3. Describe each step to reproduce the issue or behaviour.
see Screenshots

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by hlohaus** [comment]
The language depends on subshop and subshopID an the main shop...
It will also not work for frontend user.

**Comment by mnaczenski** [comment]
The field description might be misleading, but the selectbox shows the correct values. You can change the language in the customer details, not the shop. By changing this to the shopID the language would be changed on save, since the "shopID" in the details maps to "language" in the database.

Current behavior:
Auswahl_024

The correct way to fix this would be

- Rename the snippet to "Language" instead of "Shop", because this is what this field does
- Add a new field for the selection of the shop

**Comment by aherking** [comment]
Done

**Comment by shyim** [comment]
Thanks for your Contribution! :blue_heart:

**Pull request closed without merging**
