### PR TITLE
Removed extends from box-emotion.tpl

### PR DESCRIPTION
**Pull request by shyim**
## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | The extends in the file doesn't have a effect, because the file overwrite the entire box-basic.tpl. It reduces the confusion why my box-basic doesnt have a effect :D |
| BC breaks?              | no |
| Tests exists & pass?    | yes |
| Related tickets?        |  |
| How to test?            | Remove it and see nothing happens |
| Requirements met?       | Yes |

### CODE REVIEW

**Comment by roman-1983** [comment]
When `box-basic.tpl` will get a new block , then `box-emotion.tpl` won't benefit from it.

**Review by roman-1983 — COMMENTED** [review]
When `box-basic.tpl` will get a new block , then `box-emotion.tpl` won't benefit from it.

**Comment by klarstil** [comment]
@roman-1983 That's not the case 'cause `box-emotion.tpl` overrides the most upper block of the `box-basic.tpl` therefore it was superfluous to extend from `box-basic.tpl`. Even if the `{extends}` call would be in place, new blocks are not reflected in the `box-emotion.tpl`. This PR doesn't changes the behavior of the `box-emotion.tpl` at all.

**Comment by mitelg** [comment]
thanks for the PR @shyim :+1:

**Pull request closed without merging**
