### PR TITLE
Added filter events to all convert functions in LegacyStructConverter

### PR DESCRIPTION
**Pull request by FiveDigital**
This is needed to be able to convert the attributes you can add in the decorated services to the struct objects. The new events are consistent to the event `Legacy_Struct_Converter_Convert_Media` that was already present in the code. This also creates the ability to edit the storefront data in one central place.

### CODE REVIEW

**Comment by dnoegel** [comment]
Issues related to the extensibility of the LegacyStructConverter have been raised quite a lot in the forum and here, so I agree that we should fix it. But I think, we should introduce an interface instead of adding multiple events

**Comment by FiveDigital** [comment]
We can add an interface of course but I think it will be frustrating for plugin developers to implement 20 - 30 methods that just call the core service when you need to change just one of the functions.

**Comment by FiveDigital** [comment]
And here comes the interface.

**Comment by dnoegel** [comment]
Another option would be to create domain specific LegacyStructConverts and to give them a meaningful interface - so the default LegacyStructConverter would just be a facade for those. Any opinions for that? This is not asking to implement it right away - just gather some opinions :)

**Comment by shyim** [comment]
We could also do like

``` php
public function __call($function, $args) {
return call_user_func_array([$this->parentLegacyConverter, $function], $args);
}
```

**Comment by FiveDigital** [comment]
@shyim No ... 

@dnoegel I had the same idea when creating the interface. It should be discussed wether the `LegacyStructConverter` should keep it's methods and call the same function on other the other converters (injected in the constructor) or not.

My proposal for a split tbd:

``` php
interface ShopStructConverterInterface
{
    public function convertCountryStructList($countries);

    public function convertCountryStruct(StoreFrontBundle\Struct\Country $country);

    public function convertStateStructList($states);

    public function convertStateStruct(StoreFrontBundle\Struct\Country\State $state);
}

interface CategoryStructConverterInterface
{
    public function convertCategoryStruct(StoreFrontBundle\Struct\Category $category);
}

interface ProductStructConverterInterface
{
    public function convertListProductStructList(array $products);

    public function convertListProductStruct(StoreFrontBundle\Struct\ListProduct $product);

    public function convertProductStruct(StoreFrontBundle\Struct\Product $product);

    public function convertPriceStruct(StoreFrontBundle\Struct\Product\Price $price);

    public function convertUnitStruct(StoreFrontBundle\Struct\Product\Unit $unit);
}

interface PropertyStructConverterInterface
{
    public function convertPropertySetStruct(StoreFrontBundle\Struct\Property\Set $set);

    public function convertPropertyGroupStruct(StoreFrontBundle\Struct\Property\Group $group);

    public function convertPropertyOptionStruct(StoreFrontBundle\Struct\Property\Option $option);
}

interface ManufacturerStructConverterInterface
{
    public function convertManufacturerStruct(StoreFrontBundle\Struct\Product\Manufacturer $manufacturer);
}

interface MediaStructConverterInterface
{
    public function convertMediaStruct(StoreFrontBundle\Struct\Media $media);
}

interface MarketingStructConverterInterface
{
    public function convertRelatedProductStreamStruct(StoreFrontBundle\Struct\ProductStream $productStream);

    public function convertVoteAverageStruct(StoreFrontBundle\Struct\Product\VoteAverage $average);

    public function convertVoteStruct(StoreFrontBundle\Struct\Product\Vote $vote);
}

interface ConfiguratorStructConverterInterface
{
    public function convertConfiguratorGroupStruct(StoreFrontBundle\Struct\Configurator\Group $group);

    public function convertConfiguratorStruct(
        StoreFrontBundle\Struct\ListProduct $product,
        StoreFrontBundle\Struct\Configurator\Set $set
    );

    public function convertConfiguratorPrice(
        StoreFrontBundle\Struct\ListProduct $product,
        StoreFrontBundle\Struct\Configurator\Set $set
    );

    public function convertConfiguratorOptionStruct(
        StoreFrontBundle\Struct\Configurator\Group $group,
        StoreFrontBundle\Struct\Configurator\Option $option
    );
}
```

**Comment by dnoegel** [comment]
@FiveDigital: Exactly. It wouldn't even introduce any breaks as long the LegacyStructConverter is still in place.

**Comment by FiveDigital** [comment]
So will you merge my PR and add the other StructConverter classes or should I extend my PR?

**Comment by FiveDigital** [comment]
ping @dnoegel

**Comment by bcremer** [comment]
@FiveDigital Daniel is on holiday right now. Your PR is `scheduled` so we will work on it in one of our next sprints.

**Pull request closed without merging**
