### PR TITLE
Renamed Shopware.model.AttributeConfig to Shopware.apps.Base.model.AttributeConfig

### PR DESCRIPTION
**Pull request by oktupol**
## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | This fixes a consistency flaw. The class now follows the same naming scheme as all other classes in this directory. |
| BC breaks?              | no, old class name is still defined as alternateClassName |
| Tests exists & pass?    | yes |
| Related tickets?        |  |
| How to test?            | see below |
| Requirements met?       | yes |

### How to test
Test, if new class name works:
```javascript
// In developer console
Ext.create('Shopware.apps.Base.model.AttributeConfig');
```

Test, if old class name still works
```javascript
// In developer console
Ext.create('Shopware.model.AttributeConfig');
```

### CODE REVIEW

**Comment by mitelg** [comment]
thanks @oktupol :+1:

**Comment by htkassner** [comment]
Sorry @oktupol, but this commit has to be reverted, because there are some problems opening several modules. It is correct that the model can be instantiated via both names but it seems that the way the attribute plugin is loaded into several modules requires the old model class name. Thank you anyways.

**Comment by oktupol** [comment]
I see. Wouldn't it be better to rename those occurrences as well though?

**Comment by htkassner** [comment]
I guess the benefit of a renaming is too small in this case compared to the issues we had and the unexpected ones it may cause. I hope you understand that.

**Pull request closed without merging**
