### PR TITLE
Join s_order_basket_attributes in sGetDispatchBasket

### PR DESCRIPTION
**Pull request by GerDner**
## Description

Please describe your pull request:
- Why is it necessary? If you want to calculate shipping costs based on bundle informations you need the s_order_basket_attributes table joined.
- What does it improve? More fields for the Field "Calculation" in the dispatch modul. (e.g For Bundle or AboCommerce)
- Does it have side effects?
  no

| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? | none |
| How to test? | Use fields in your own calculation. For example count bundles with "COUNT(DISTINCT  ba.bundle_id)" |

### CODE REVIEW

**Comment by hlohaus** [comment]
Hey,

you shoud extends the dispatch query in the product export too.
https://github.com/shopware/shopware/blob/5.2/engine/Shopware/Core/sExport.php#L1330
Or the select on the attr table generated there an error.

Alternatively, you can also use a subselect . Then the JOIN is not need.

Heiner

**Comment by GerDner** [comment]
Thx for the feedback. I changed sExports as well.

**Comment by danielwolf1** [comment]
The change is only available in sExport as the build process failed for sAdmin - does anyone know something about this case?

**Comment by mitelg** [comment]
hey @danielwolf1 
we reverted the changes in 1a9d4660695 and in e8151e27073

**Comment by danielwolf1** [comment]
OK, because it crashed during Export_ We store additional information about a basket in s_order_basket_attributes which are important to calculate shipping costs. What about adding a notify-Filter to extend the query if needed?

**Comment by mitelg** [comment]
@danielwolf1 yes, that could be done. If you like, just create an own PR oder an issue ticket on https://issues.shopware.com :wink:

**Pull request closed without merging**
