### PR TITLE
add missing Countries

### PR DESCRIPTION
**Pull request by tinect**
### 1. Why is this change necessary?
some countries are missing. data based on https://restcountries.eu

### 2. What does this change do, exactly?
adding missing countries

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by tinect** [comment]
Merry Christmas @soebbing :-)

**Comment by shyim** [comment]
Hey @tinect,

your new Migration is failing :wink:

**Comment by tinect** [comment]
@shyim let us give him an second chance :-)

**Comment by shyim** [comment]
@tinect thanks for the contribution!  :blue_heart:

**Pull request closed without merging**
