### PR TITLE
Use Shopware container as container property class

### PR DESCRIPTION
**Pull request by shyim**
## Description

| Questions               | Answers |
|-------------------------|-------------------------------------------------------|
| Why?                    | ContainerInterface doesn't provide all shopware container methodes like initialized |
| BC breaks?              | no |
| Tests exists & pass?    | yes |
| Related tickets?        |  |
| How to test?            | Use method initialized and you got a phpstorm warning |
| Requirements met?       | Yes |

### CODE REVIEW

**Comment by shyim** [comment]
CDN is broken :(

**Comment by giginos** [comment]
If these methods are really "required" - wouldn't it be better to define them in ContainerInterface or create a new ExtendedContainerInterface containing them?

**Comment by shyim** [comment]
It was not possible to modify the Shopware default ContainerAwareInterface to ContainerInterface, because it would introduce many bc-breaks. It could be done with 5.4 :)

**Comment by shyim** [comment]
ok

**Pull request closed without merging**
