### PR TITLE
FormSynchronizer use sorting from config.xml

### PR DESCRIPTION
**Pull request by shyim**
### 1. Why is this change necessary?
Use sorting from Plugin config.xml

### 2. What does this change do, exactly?
Added position to FormSynchronizer

### 3. Describe each step to reproduce the issue or behaviour.
Create a plugin with a config option, make a plugin update and add a config option as first. The sort should be the same as config.xml

### 4. Please link to the relevant issues (if any).
https://issues.shopware.com/issues/SW-21153

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [X] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
@shopwareBot Pong

**Comment by tinect** [comment]
@shyim @mitelg Ping :-)

**Comment by Mardl** [comment]
@shyim @mitelg nothing happens :-(

**Comment by larsbo** [comment]
@Mardl it might help if you add some funny meme to the discussion (like in #1542 ) 😏

**Pull request closed without merging**
