### PR TITLE
Add attributes to configurator groups and options

### PR DESCRIPTION
**Pull request by FiveDigital**
| Questions | Answers |
| --- | --- |
| BC breaks? | no |
| Tests pass? | yes |
| Related tickets? |  |
| How to test? | It's now possible to add attributes to configurator groups and options in the backend. The attributes can be set when editing a configurator group or option. |
## Description
- Why is it necessary?

We need to extend the configurator options to add a media selection for one of our customers. I also included the configurator groups because this might become useful, too.
- What does it improve?

This was already prepared in the `LegacyStructConverter` but missing in the backend and models. 
- Does it have side effects?

No

### CODE REVIEW

**Comment by FiveDigital** [comment]
I know we should not ping but we need this merged for one of our Enterprise customer's project. Since there is no feedback yet, please have a look at my PR. I think it is easy to merge because it add's functionality that is already present on other entities and was just missing for configurator options and groups.

**Comment by dnoegel** [comment]
@OliverSkroblin Sieht gut aus, oder?

**Comment by janbuecker** [comment]
I'll import it so we can have a deeper look into it.

**Comment by FiveDigital** [comment]
If I should rebase this PR because of the migration filename, please let me know.

**Comment by janbuecker** [comment]
No action needed, we'll keep an eye on the migration number in our workflow. :)

**Comment by FiveDigital** [comment]
Are you going to merge this PR since the partner attributes PR (https://github.com/shopware/shopware/pull/896) has been merged, too ... within 4 days instead of 4 month :stuck_out_tongue: :point_up:

**Pull request closed without merging**
