### PR TITLE
Fixed plugin cronjob.xml boolean evaluation

### PR DESCRIPTION
**Pull request by nlubisch**
## Description
Please describe your pull request:
* Why is it necessary? if an boolean value equals integer 1 the value got evaluated as false
* What does it improve? boolean evaluation
* Does it have side effects? no

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes/no
| How to test?     |  install plugin [LubischTest_cronjob_bool.zip](https://github.com/shopware/shopware/files/740228/LubischTest_cronjob_bool.zip) - the configured "disableOnError" with 1 gets evaluated and saved as 0.

Reference: https://www.w3.org/TR/xmlschema11-2/#boolean

### CODE REVIEW

**Comment by Haehnchen** [comment]
:thumbsup:

**Comment by janbuecker** [comment]
Thanks @nlubisch, looks good to me. I'll schedule this change and do some testing on it. 👍

**Comment by nlubisch** [comment]
Im working on some changes to the xml reader, like refactor all readers because they share the most functionality and would test it to near 100% code coverage. IMO It looks a bit nasty because each reader does their own thing.

**Comment by mitelg** [comment]
thanks for your contribution @nlubisch :+1:

**Pull request closed without merging**
