### PR TITLE
Added Guetzli media optimizer

### PR DESCRIPTION
**Pull request by shyim**
## Description
Please describe your pull request:
* Why is it necessary?
Supporting Google guetzli optimizer
* What does it improve?
Adds guetzli support
* Does it have side effects?
Nope

| Questions        | Answers
| ---------------- | -------------------------------------------------------
| BC breaks?       | no
| Tests pass?      | yes
| Related tickets? | 
| How to test?     | Install guetzli (https://github.com/google/guetzli) and run optimizer

### CODE REVIEW

**Comment by janbuecker** [comment]
+1

I think we should raise the priority to run guetzli as first optimizer. /cc @MarcelSchmaeing @Phil23

**Comment by shyim** [comment]
@janbuecker done :)

**Comment by Phil23** [comment]
Please provide info in the upgrade.md file.

**Comment by bcremer** [comment]
@janbuecker Please keep in mind that `guetzli` is known to be very very slow before raising the priority. 

Please see:   
- https://www.theregister.co.uk/2017/03/17/google_guetzli_compression_algorithm/
- https://github.com/google/guetzli/issues/50

**Comment by shyim** [comment]
@Phil23 done :)

**Comment by Phil23** [comment]
@shyim,

please avoid doing merge commits for rebase purposes. Please make sure to only do a normal rebase on the correct version branch to keep the history correct. Makes it harder to merge your changes.

Also squash all changes in one single commit with meaningful commit message.

Thx!

**Comment by janbuecker** [comment]
Good hint, thanks @bcremer.

**Comment by shyim** [comment]
@Phil23 is merged into one

**Pull request closed without merging**
