### PR TITLE
Add SQL filter event to the check if an article is already in the basket

### PR DESCRIPTION
**Pull request by andrewisplinghoff**
With this, plugins can influence how the basket determines equality of articles when adding a new article. This filter event is needed by plugins that extend the article model in a way so that it is not enough anymore to just check if order numbers are equal.

### CODE REVIEW

**Comment by bcremer** [comment]
Thanks for you contribution.
Generally the additional event seems reasonably to me.

But can you please rewrite the query to use the DBAL query builder instead (`Shopware()->Models()->getConnection()->createQueryBuilder()`) and emit the query builder in a notify event.

We don't want to include more filterSQL events on plain SQL strings, because they are not really extendable in a sane way.

**Comment by andrewisplinghoff** [comment]
Thanks for the fast feedback. Any more issues? Should I squash the commits?

**Comment by bcremer** [comment]
Yes, please squash the commits.

Looks good to me, I'll do the final review tomorrow.

**Comment by bcremer** [comment]
Please note that I changed the event from `filter` to a `notify` event, see example listener:

```
$this->eventManager->addListener(
    'Shopware_Modules_Basket_AddArticle_CheckBasketForArticle',
    function (Enlight_Event_EventArgs $eventArgs) {
        /** @var \Doctrine\DBAL\Query\QueryBuilder $qb */
        $qb = $eventArgs->get('queryBuilder');
        $qb->andWhere('somefoo = somebar');
    }
);
```

Thanks again for your contribution :+1:

**Pull request merged**
