### PR TITLE
Remove unknown sprite-user-silhouette-question selector

### PR DESCRIPTION
**Pull request by DanielRuf**
### 1. Why is this change necessary?
There is a wrong selector which is there as a class name already.

### 2. What does this change do, exactly?
Remove the wrong selector as there is no `<sprite-user-silhouette-question/>`.

### 6. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have squashed any insignificant commits
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by shyim** [comment]
Hi @DanielRuf, thank you very much for your contribution! :blue_heart:

**Comment by DanielRuf** [comment]
> Hi @DanielRuf, thank you very much for your contribution! 💙

Which was not merged ;-)
I guess all other PRs of me will be also closed without being merged.

**Comment by shyim** [comment]
It is merged, but currently not synced to Github :wink:

**Comment by DanielRuf** [comment]
> It is merged, but currently not synced to Github 😉

Ah ok, thanks for the clarification. I guess the "commit and push as often as possible" approach that I apply to my teams is different here and it is irritating that it was not done by the shopwareBot account ;-)

**Comment by soebbing** [comment]
We do not work on Github directly, but instead use an On-premise Stash for e.g. internal feature branches and PRs, or to fix and release security issues before publishing them. Only the development branches of the main versions are pushed to Github.
This is also the reason we prefer larger PRs (with atomic commits), since importing theses PRs into our local system isn't frictionless.

**Pull request closed without merging**
