### PR TITLE
Add svg format to $fileUploadBlacklist

### PR DESCRIPTION
**Pull request by yazgx97**
### 1. Why is this change necessary?
The .svg file format allows the insertion and execution of arbitrary javascript leading to XSS attacks

### 2. What does this change do, exactly?
Do not allow uploading .svg image files to the server

### 3. Describe each step to reproduce the issue or behaviour.
The step to reproduce the issue is described in detail in the report: [https://huntr.dev/bounties/778474ad-8ee4-48a6-8562-7c56ee222d44/](https://huntr.dev/bounties/778474ad-8ee4-48a6-8562-7c56ee222d44/)

### 4. Please link to the relevant issues (if any).
[https://huntr.dev/bounties/778474ad-8ee4-48a6-8562-7c56ee222d44/](https://huntr.dev/bounties/778474ad-8ee4-48a6-8562-7c56ee222d44/)

### 6. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed any insignificant commits
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfil them.

### CODE REVIEW

**Comment by yazgx97** [comment]
@mitelg Hi maintainer, I found some bug on your application and disclose it on the [huntr.dev](huntr.dev) platform. Because the issue cannot be created, the huntr's system cannot email you the vulnerability notification.

Link report
1. Stored XSS: https://huntr.dev/bounties/778474ad-8ee4-48a6-8562-7c56ee222d44/
2. Unrestricted Upload of File with Dangerous Type: https://huntr.dev/bounties/3fc2a181-fc32-4bbf-9f8d-8cd748054fa5/

Can you access huntr platform with maintainer account to confirm reports.

**Comment by mitelg** [comment]
hey @noobpk 
we will address the first issue in the ticket mentioned above. 

please create a ticket for the second issue on our issue tracker. you can select "security issue" there: https://issues.shopware.com/createissue

**Comment by yazgx97** [comment]
HI @mgrl,
I have created a ticket for the second issue with ID: SW-26368

If you confirm two issue's, pls help me validate them on [huntr](https://huntr.dev). Don't worry about bounty, huntr will pay for this . 

Thank

**Comment by teiling88** [comment]
Don't get me wrong but if you give an untrusted user backend access, is a svg upload your smallest issue.

I don't see this as a security issue cause then is a zip file with countains php files for the plugin manager much more risky.

This is only possibly in the backend area where you have to give explicite somebody access to.

**Comment by yazgx97** [comment]
> Don't get me wrong but if you give an untrusted user backend access, is a svg upload your smallest issue.
> 
> I don't see this as a security issue cause then is a zip file with countains php files for the plugin manager much more risky.
> 
> This is only possibly in the backend area where you have to give explicite somebody access to.

Most of the incidents that occur are due to user negligence. The account of a low-level administrator may be exposed somewhere or have the password bruteforced. From there the attacker can access and perform attacks to gain higher authority.

**Comment by mitelg** [comment]
hey @noobpk 

thanks for bringing up this issue. We just released a security update (5.7.6) to address this authenticated stored XSS
We could not use your fix, because disallowing svg uploads would be a feature loss. Instead we made an addition to the `.htaccess` file to prevent the execution of the malicious code. 

Thanks again and best regards :slightly_smiling_face:  :wave:

**Pull request closed without merging**
